using System;
using TechTalk.SpecFlow;
using Spartan.Core.WinForms.WinFormsObjects;
using Spartan.Core.WinForms;
using Spartan.Core;

namespace SCRIPAU.Automation.Screens
{
    [Binding]
    public class OLSB0106

    {
		//Form Object
		public static WinFormsForm FormName = new WinFormsForm("OLSB0106", "FormName");
		//Fields


        public static WinFormsField SystemInfoFree6 = new WinFormsField("SYSTEM-INFO-FREE-6", "20", "20");
        public static WinFormsField SystemInfoFree7 = new WinFormsField("SYSTEM-INFO-FREE-7", "21", "21");
        public static WinFormsField SystemInfoFree4 = new WinFormsField("SYSTEM-INFO-FREE-4", "18", "18");
        public static WinFormsField BulkID1 = new WinFormsField("BULK-ID-1", "BulkID1");
        public static WinFormsField Currency1 = new WinFormsField("CURRENCY-1", "Currency1");
        public static WinFormsField SettlementDate1 = new WinFormsField("SETTLEMENT-DATE-1", "SettlementDate1");
        public static WinFormsField ProcessBulkInd1 = new WinFormsField("PROCESS-BULK-IND-1", "ProcessBulkInd1");
        public static WinFormsField BulkID16 = new WinFormsField("BULK-ID-16", "BulkID16");
        public static WinFormsField Currency16 = new WinFormsField("CURRENCY-16", "Currency16");
        public static WinFormsField SettlementDate16 = new WinFormsField("SETTLEMENT-DATE-16", "SettlementDate16");
        public static WinFormsField ProcessBulkInd16 = new WinFormsField("PROCESS-BULK-IND-16", "ProcessBulkInd16");
        public static WinFormsField BulkID2 = new WinFormsField("BULK-ID-2", "BulkID2");
        public static WinFormsField Currency2 = new WinFormsField("CURRENCY-2", "Currency2");
        public static WinFormsField SettlementDate2 = new WinFormsField("SETTLEMENT-DATE-2", "SettlementDate2");
        public static WinFormsField ProcessBulkInd2 = new WinFormsField("PROCESS-BULK-IND-2", "ProcessBulkInd2");
        public static WinFormsField BulkID17 = new WinFormsField("BULK-ID-17", "BulkID17");
        public static WinFormsField Currency17 = new WinFormsField("CURRENCY-17", "Currency17");
        public static WinFormsField SettlementDate17 = new WinFormsField("SETTLEMENT-DATE-17", "SettlementDate17");
        public static WinFormsField ProcessBulkInd17 = new WinFormsField("PROCESS-BULK-IND-17", "ProcessBulkInd17");
        public static WinFormsField BulkID3 = new WinFormsField("BULK-ID-3", "BulkID3");
        public static WinFormsField Currency3 = new WinFormsField("CURRENCY-3", "Currency3");
        public static WinFormsField SettlementDate3 = new WinFormsField("SETTLEMENT-DATE-3", "SettlementDate3");
        public static WinFormsField ProcessBulkInd3 = new WinFormsField("PROCESS-BULK-IND-3", "ProcessBulkInd3");
        public static WinFormsField BulkID18 = new WinFormsField("BULK-ID-18", "BulkID18");
        public static WinFormsField Currency18 = new WinFormsField("CURRENCY-18", "Currency18");
        public static WinFormsField SettlementDate18 = new WinFormsField("SETTLEMENT-DATE-18", "SettlementDate18");
        public static WinFormsField ProcessBulkInd18 = new WinFormsField("PROCESS-BULK-IND-18", "ProcessBulkInd18");
        public static WinFormsField BulkID4 = new WinFormsField("BULK-ID-4", "BulkID4");
        public static WinFormsField Currency4 = new WinFormsField("CURRENCY-4", "Currency4");
        public static WinFormsField SettlementDate4 = new WinFormsField("SETTLEMENT-DATE-4", "SettlementDate4");
        public static WinFormsField ProcessBulkInd4 = new WinFormsField("PROCESS-BULK-IND-4", "ProcessBulkInd4");
        public static WinFormsField BulkID19 = new WinFormsField("BULK-ID-19", "BulkID19");
        public static WinFormsField Currency19 = new WinFormsField("CURRENCY-19", "Currency19");
        public static WinFormsField SettlementDate19 = new WinFormsField("SETTLEMENT-DATE-19", "SettlementDate19");
        public static WinFormsField ProcessBulkInd19 = new WinFormsField("PROCESS-BULK-IND-19", "ProcessBulkInd19");
        public static WinFormsField BulkID5 = new WinFormsField("BULK-ID-5", "BulkID5");
        public static WinFormsField Currency5 = new WinFormsField("CURRENCY-5", "Currency5");
        public static WinFormsField Settlement5date5 = new WinFormsField("SETTLEMENT5DATE-5", "Settlement5date5");
        public static WinFormsField ProcessBulkInd5 = new WinFormsField("PROCESS-BULK-IND-5", "ProcessBulkInd5");
        public static WinFormsField BulkID20 = new WinFormsField("BULK-ID-20", "BulkID20");
        public static WinFormsField Currency20 = new WinFormsField("CURRENCY-20", "Currency20");
        public static WinFormsField SettlementDate20 = new WinFormsField("SETTLEMENT-DATE-20", "SettlementDate20");
        public static WinFormsField ProcessBulkInd20 = new WinFormsField("PROCESS-BULK-IND-20", "ProcessBulkInd20");
        public static WinFormsField BulkID6 = new WinFormsField("BULK-ID-6", "BulkID6");
        public static WinFormsField Currency6 = new WinFormsField("CURRENCY-6", "Currency6");
        public static WinFormsField SettlementDate6 = new WinFormsField("SETTLEMENT-DATE-6", "SettlementDate6");
        public static WinFormsField ProcessBulkInd6 = new WinFormsField("PROCESS-BULK-IND-6", "ProcessBulkInd6");
        public static WinFormsField BulkID21 = new WinFormsField("BULK-ID-21", "BulkID21");
        public static WinFormsField Currency21 = new WinFormsField("CURRENCY-21", "Currency21");
        public static WinFormsField SettlementDate21 = new WinFormsField("SETTLEMENT-DATE-21", "SettlementDate21");
        public static WinFormsField ProcessBulkInd21 = new WinFormsField("PROCESS-BULK-IND-21", "ProcessBulkInd21");
        public static WinFormsField BulkID7 = new WinFormsField("BULK-ID-7", "BulkID7");
        public static WinFormsField Currency7 = new WinFormsField("CURRENCY-7", "Currency7");
        public static WinFormsField SettlementDate7 = new WinFormsField("SETTLEMENT-DATE-7", "SettlementDate7");
        public static WinFormsField ProcessBulkInd7 = new WinFormsField("PROCESS-BULK-IND-7", "ProcessBulkInd7");
        public static WinFormsField BulkID22 = new WinFormsField("BULK-ID-22", "BulkID22");
        public static WinFormsField Currency22 = new WinFormsField("CURRENCY-22", "Currency22");
        public static WinFormsField SettlementDate22 = new WinFormsField("SETTLEMENT-DATE-22", "SettlementDate22");
        public static WinFormsField ProcessBulkInd22 = new WinFormsField("PROCESS-BULK-IND-22", "ProcessBulkInd22");
        public static WinFormsField BulkID8 = new WinFormsField("BULK-ID-8", "BulkID8");
        public static WinFormsField Currency8 = new WinFormsField("CURRENCY-8", "Currency8");
        public static WinFormsField SettlementDate8 = new WinFormsField("SETTLEMENT-DATE-8", "SettlementDate8");
        public static WinFormsField ProcessBulkInd8 = new WinFormsField("PROCESS-BULK-IND-8", "ProcessBulkInd8");
        public static WinFormsField BulkID23 = new WinFormsField("BULK-ID-23", "BulkID23");
        public static WinFormsField Currency23 = new WinFormsField("CURRENCY-23", "Currency23");
        public static WinFormsField SettlementDate23 = new WinFormsField("SETTLEMENT-DATE-23", "SettlementDate23");
        public static WinFormsField ProcessBulkInd23 = new WinFormsField("PROCESS-BULK-IND-23", "ProcessBulkInd23");
        public static WinFormsField BulkID9 = new WinFormsField("BULK-ID-9", "BulkID9");
        public static WinFormsField Currency9 = new WinFormsField("CURRENCY-9", "Currency9");
        public static WinFormsField SettlementDate9 = new WinFormsField("SETTLEMENT-DATE-9", "SettlementDate9");
        public static WinFormsField ProcessBulkInd9 = new WinFormsField("PROCESS-BULK-IND-9", "ProcessBulkInd9");
        public static WinFormsField BulkID24 = new WinFormsField("BULK-ID-24", "BulkID24");
        public static WinFormsField Currency24 = new WinFormsField("CURRENCY-24", "Currency24");
        public static WinFormsField SettlementDate24 = new WinFormsField("SETTLEMENT-DATE-24", "SettlementDate24");
        public static WinFormsField ProcessBulkInd24 = new WinFormsField("PROCESS-BULK-IND-24", "ProcessBulkInd24");
        public static WinFormsField BulkID10 = new WinFormsField("BULK-ID-10", "BulkID10");
        public static WinFormsField Currency10 = new WinFormsField("CURRENCY-10", "Currency10");
        public static WinFormsField SettlementDate10 = new WinFormsField("SETTLEMENT-DATE-10", "SettlementDate10");
        public static WinFormsField ProcessBulkInd10 = new WinFormsField("PROCESS-BULK-IND-10", "ProcessBulkInd10");
        public static WinFormsField BulkID25 = new WinFormsField("BULK-ID-25", "BulkID25");
        public static WinFormsField Currency25 = new WinFormsField("CURRENCY-25", "Currency25");
        public static WinFormsField SettlementDate25 = new WinFormsField("SETTLEMENT-DATE-25", "SettlementDate25");
        public static WinFormsField ProcessBulkInd25 = new WinFormsField("PROCESS-BULK-IND-25", "ProcessBulkInd25");
        public static WinFormsField BulkID11 = new WinFormsField("BULK-ID-11", "BulkID11");
        public static WinFormsField Currency11 = new WinFormsField("CURRENCY-11", "Currency11");
        public static WinFormsField SettlementDate11 = new WinFormsField("SETTLEMENT-DATE-11", "SettlementDate11");
        public static WinFormsField ProcessBulkInd11 = new WinFormsField("PROCESS-BULK-IND-11", "ProcessBulkInd11");
        public static WinFormsField BulkID26 = new WinFormsField("BULK-ID-26", "BulkID26");
        public static WinFormsField Currency26 = new WinFormsField("CURRENCY-26", "Currency26");
        public static WinFormsField SettlementDate26 = new WinFormsField("SETTLEMENT-DATE-26", "SettlementDate26");
        public static WinFormsField ProcessBulkInd26 = new WinFormsField("PROCESS-BULK-IND-26", "ProcessBulkInd26");
        public static WinFormsField BulkID12 = new WinFormsField("BULK-ID-12", "BulkID12");
        public static WinFormsField Currency12 = new WinFormsField("CURRENCY-12", "Currency12");
        public static WinFormsField SettlementDate12 = new WinFormsField("SETTLEMENT-DATE-12", "SettlementDate12");
        public static WinFormsField ProcessBulkInd12 = new WinFormsField("PROCESS-BULK-IND-12", "ProcessBulkInd12");
        public static WinFormsField BulkID27 = new WinFormsField("BULK-ID-27", "BulkID27");
        public static WinFormsField Currency27 = new WinFormsField("CURRENCY-27", "Currency27");
        public static WinFormsField SettlementDate27 = new WinFormsField("SETTLEMENT-DATE-27", "SettlementDate27");
        public static WinFormsField ProcessBulkInd27 = new WinFormsField("PROCESS-BULK-IND-27", "ProcessBulkInd27");
        public static WinFormsField BulkID13 = new WinFormsField("BULK-ID-13", "BulkID13");
        public static WinFormsField Currency13 = new WinFormsField("CURRENCY-13", "Currency13");
        public static WinFormsField SettlementDate13 = new WinFormsField("SETTLEMENT-DATE-13", "SettlementDate13");
        public static WinFormsField ProcessBulkInd13 = new WinFormsField("PROCESS-BULK-IND-13", "ProcessBulkInd13");
        public static WinFormsField BulkID28 = new WinFormsField("BULK-ID-28", "BulkID28");
        public static WinFormsField Currency28 = new WinFormsField("CURRENCY-28", "Currency28");
        public static WinFormsField SettlementDate28 = new WinFormsField("SETTLEMENT-DATE-28", "SettlementDate28");
        public static WinFormsField ProcessBulkInd28 = new WinFormsField("PROCESS-BULK-IND-28", "ProcessBulkInd28");
        public static WinFormsField BulkID14 = new WinFormsField("BULK-ID-14", "BulkID14");
        public static WinFormsField Currency14 = new WinFormsField("CURRENCY-14", "Currency14");
        public static WinFormsField SettlementDate14 = new WinFormsField("SETTLEMENT-DATE-14", "SettlementDate14");
        public static WinFormsField ProcessBulkInd14 = new WinFormsField("PROCESS-BULK-IND-14", "ProcessBulkInd14");
        public static WinFormsField BulkID29 = new WinFormsField("BULK-ID-29", "BulkID29");
        public static WinFormsField Currency29 = new WinFormsField("CURRENCY-29", "Currency29");
        public static WinFormsField SettlementDate29 = new WinFormsField("SETTLEMENT-DATE-29", "SettlementDate29");
        public static WinFormsField ProcessBulkInd29 = new WinFormsField("PROCESS-BULK-IND-29", "ProcessBulkInd29");
        public static WinFormsField BulkID15 = new WinFormsField("BULK-ID-15", "BulkID15");
        public static WinFormsField Currency15 = new WinFormsField("CURRENCY-15", "Currency15");
        public static WinFormsField SettlementDate15 = new WinFormsField("SETTLEMENT-DATE-15", "SettlementDate15");
        public static WinFormsField ProcessBulkInd15 = new WinFormsField("PROCESS-BULK-IND-15", "ProcessBulkInd15");
        public static WinFormsField BulkID30 = new WinFormsField("BULK-ID-30", "BulkID30");
        public static WinFormsField Currency30 = new WinFormsField("CURRENCY-30", "Currency30");
        public static WinFormsField SettlementDate30 = new WinFormsField("SETTLEMENT-DATE-30", "SettlementDate30");
        public static WinFormsField ProcessBulkInd30 = new WinFormsField("PROCESS-BULK-IND-30", "ProcessBulkInd30");
        public static WinFormsField SystemInfoFree5 = new WinFormsField("SYSTEM-INFO-FREE-5", "19", "19");
    }
}
