using System;
using TechTalk.SpecFlow;
using Spartan.Core.WinForms.WinFormsObjects;
using Spartan.Core.WinForms;
using Spartan.Core;

namespace SCRIPAU.Automation.Screens
{
    [Binding]
    public class PXS02501

    {
		//Form Object
		public static WinFormsForm FormName = new WinFormsForm("PXS02501", "FormName");
		//Fields
        public static WinFormsField NbrMtgClasses = new WinFormsField("NBR-MTG-CLASSES", "NbrMtgClasses");
        public static WinFormsField HolderID = new WinFormsField("HOLDER-ID", "HolderID");
        public static WinFormsField AddressLine = new WinFormsField("ADDRESS-LINE", "AddressLine");
        public static WinFormsField RefNumber = new WinFormsField("REF-NUMBER", "RefNumber");
        public static WinFormsField ClassesLeft = new WinFormsField("CLASSES-LEFT", "ClassesLeft");
        public static WinFormsField ClassCode = new WinFormsField("CLASS-CODE", "ClassCode");
        public static WinFormsField ClassEntitlement = new WinFormsField("CLASS-ENTITLEMENT", "ClassEntitlement");
        public static WinFormsField ResDesc = new WinFormsField("RES-DESC", "ResDesc");
        public static WinFormsField For01 = new WinFormsField("FOR-01", "For01");
        public static WinFormsField Against01 = new WinFormsField("AGAINST-01", "Against01");
        public static WinFormsField OpenTicked01 = new WinFormsField("OPEN-TICKED-01", "OpenTicked01");
        public static WinFormsField OpenUnticked01 = new WinFormsField("OPEN-UNTICKED-01", "OpenUnticked01");
        public static WinFormsField Abstain01 = new WinFormsField("ABSTAIN-01", "Abstain01");
        public static WinFormsField Exclude01 = new WinFormsField("EXCLUDE-01", "Exclude01");
        public static WinFormsField For02 = new WinFormsField("FOR-02", "For02");
        public static WinFormsField Against02 = new WinFormsField("AGAINST-02", "Against02");
        public static WinFormsField OpenTicked02 = new WinFormsField("OPEN-TICKED-02", "OpenTicked02");
        public static WinFormsField OpenUnticked02 = new WinFormsField("OPEN-UNTICKED-02", "OpenUnticked02");
        public static WinFormsField Abstain02 = new WinFormsField("ABSTAIN-02", "Abstain02");
        public static WinFormsField Exclude02 = new WinFormsField("EXCLUDE-02", "Exclude02");
        public static WinFormsField For03 = new WinFormsField("FOR-03", "For03");
        public static WinFormsField Against03 = new WinFormsField("AGAINST-03", "Against03");
        public static WinFormsField OpenTicked03 = new WinFormsField("OPEN-TICKED-03", "OpenTicked03");
        public static WinFormsField OpenUnticked03 = new WinFormsField("OPEN-UNTICKED-03", "OpenUnticked03");
        public static WinFormsField Abstain03 = new WinFormsField("ABSTAIN-03", "Abstain03");
        public static WinFormsField Exclude03 = new WinFormsField("EXCLUDE-03", "Exclude03");
        public static WinFormsField For04 = new WinFormsField("FOR-04", "For04");
        public static WinFormsField Against04 = new WinFormsField("AGAINST-04", "Against04");
        public static WinFormsField OpenTicked04 = new WinFormsField("OPEN-TICKED-04", "OpenTicked04");
        public static WinFormsField OpenUnticked04 = new WinFormsField("OPEN-UNTICKED-04", "OpenUnticked04");
        public static WinFormsField Abstain04 = new WinFormsField("ABSTAIN-04", "Abstain04");
        public static WinFormsField Exclude04 = new WinFormsField("EXCLUDE-04", "Exclude04");
        public static WinFormsField For05 = new WinFormsField("FOR-05", "For05");
        public static WinFormsField Against05 = new WinFormsField("AGAINST-05", "Against05");
        public static WinFormsField OpenTicked05 = new WinFormsField("OPEN-TICKED-05", "OpenTicked05");
        public static WinFormsField OpenUnticked05 = new WinFormsField("OPEN-UNTICKED-05", "OpenUnticked05");
        public static WinFormsField Abstain05 = new WinFormsField("ABSTAIN-05", "Abstain05");
        public static WinFormsField Exclude05 = new WinFormsField("EXCLUDE-05", "Exclude05");
        public static WinFormsField For06 = new WinFormsField("FOR-06", "For06");
        public static WinFormsField Against06 = new WinFormsField("AGAINST-06", "Against06");
        public static WinFormsField OpenTicked06 = new WinFormsField("OPEN-TICKED-06", "OpenTicked06");
        public static WinFormsField OpenUnticked06 = new WinFormsField("OPEN-UNTICKED-06", "OpenUnticked06");
        public static WinFormsField Abstain06 = new WinFormsField("ABSTAIN-06", "Abstain06");
        public static WinFormsField Exclude06 = new WinFormsField("EXCLUDE-06", "Exclude06");
        public static WinFormsField For07 = new WinFormsField("FOR-07", "For07");
        public static WinFormsField Against07 = new WinFormsField("AGAINST-07", "Against07");
        public static WinFormsField OpenTicked07 = new WinFormsField("OPEN-TICKED-07", "OpenTicked07");
        public static WinFormsField OpenUnticked07 = new WinFormsField("OPEN-UNTICKED-07", "OpenUnticked07");
        public static WinFormsField Abstain07 = new WinFormsField("ABSTAIN-07", "Abstain07");
        public static WinFormsField Exclude07 = new WinFormsField("EXCLUDE-07", "Exclude07");
        public static WinFormsField For08 = new WinFormsField("FOR-08", "For08");
        public static WinFormsField Against08 = new WinFormsField("AGAINST-08", "Against08");
        public static WinFormsField OpenTicked08 = new WinFormsField("OPEN-TICKED-08", "OpenTicked08");
        public static WinFormsField OpenUnticked08 = new WinFormsField("OPEN-UNTICKED-08", "OpenUnticked08");
        public static WinFormsField Abstain08 = new WinFormsField("ABSTAIN-08", "Abstain08");
        public static WinFormsField Exclude08 = new WinFormsField("EXCLUDE-08", "Exclude08");
        public static WinFormsField For09 = new WinFormsField("FOR-09", "For09");
        public static WinFormsField Against09 = new WinFormsField("AGAINST-09", "Against09");
        public static WinFormsField OpenTicked09 = new WinFormsField("OPEN-TICKED-09", "OpenTicked09");
        public static WinFormsField OpenUnticked09 = new WinFormsField("OPEN-UNTICKED-09", "OpenUnticked09");
        public static WinFormsField Abstain09 = new WinFormsField("ABSTAIN-09", "Abstain09");
        public static WinFormsField Exclude09 = new WinFormsField("EXCLUDE-09", "Exclude09");
        public static WinFormsField For10 = new WinFormsField("FOR-10", "For10");
        public static WinFormsField Against10 = new WinFormsField("AGAINST-10", "Against10");
        public static WinFormsField OpenTicked10 = new WinFormsField("OPEN-TICKED-10", "OpenTicked10");
        public static WinFormsField OpenUnticked10 = new WinFormsField("OPEN-UNTICKED-10", "OpenUnticked10");
        public static WinFormsField Abstain10 = new WinFormsField("ABSTAIN-10", "Abstain10");
        public static WinFormsField Exclude10 = new WinFormsField("EXCLUDE-10", "Exclude10");
        public static WinFormsField For11 = new WinFormsField("FOR-11", "For11");
        public static WinFormsField Against11 = new WinFormsField("AGAINST-11", "Against11");
        public static WinFormsField OpenTicked11 = new WinFormsField("OPEN-TICKED-11", "OpenTicked11");
        public static WinFormsField OpenUnticked11 = new WinFormsField("OPEN-UNTICKED-11", "OpenUnticked11");
        public static WinFormsField Abstain11 = new WinFormsField("ABSTAIN-11", "Abstain11");
        public static WinFormsField Exclude11 = new WinFormsField("EXCLUDE-11", "Exclude11");
        public static WinFormsField For12 = new WinFormsField("FOR-12", "For12");
        public static WinFormsField Against12 = new WinFormsField("AGAINST-12", "Against12");
        public static WinFormsField OpenTicked12 = new WinFormsField("OPEN-TICKED-12", "OpenTicked12");
        public static WinFormsField OpenUnticked12 = new WinFormsField("OPEN-UNTICKED-12", "OpenUnticked12");
        public static WinFormsField Abstain12 = new WinFormsField("ABSTAIN-12", "Abstain12");
        public static WinFormsField Exclude12 = new WinFormsField("EXCLUDE-12", "Exclude12");
        public static WinFormsField For13 = new WinFormsField("FOR-13", "For13");
        public static WinFormsField Against13 = new WinFormsField("AGAINST-13", "Against13");
        public static WinFormsField OpenTicked13 = new WinFormsField("OPEN-TICKED-13", "OpenTicked13");
        public static WinFormsField OpenUnticked13 = new WinFormsField("OPEN-UNTICKED-13", "OpenUnticked13");
        public static WinFormsField Abstain13 = new WinFormsField("ABSTAIN-13", "Abstain13");
        public static WinFormsField Exclude13 = new WinFormsField("EXCLUDE-13", "Exclude13");
        public static WinFormsField For14 = new WinFormsField("FOR-14", "For14");
        public static WinFormsField Against14 = new WinFormsField("AGAINST-14", "Against14");
        public static WinFormsField OpenTicked14 = new WinFormsField("OPEN-TICKED-14", "OpenTicked14");
        public static WinFormsField OpenUnticked14 = new WinFormsField("OPEN-UNTICKED-14", "OpenUnticked14");
        public static WinFormsField Abstain14 = new WinFormsField("ABSTAIN-14", "Abstain14");
        public static WinFormsField Exclude14 = new WinFormsField("EXCLUDE-14", "Exclude14");
        public static WinFormsField For15 = new WinFormsField("FOR-15", "For15");
        public static WinFormsField Against15 = new WinFormsField("AGAINST-15", "Against15");
        public static WinFormsField OpenTicked15 = new WinFormsField("OPEN-TICKED-15", "OpenTicked15");
        public static WinFormsField OpenUnticked15 = new WinFormsField("OPEN-UNTICKED-15", "OpenUnticked15");
        public static WinFormsField Abstain15 = new WinFormsField("ABSTAIN-15", "Abstain15");
        public static WinFormsField Exclude15 = new WinFormsField("EXCLUDE-15", "Exclude15");
        public static WinFormsField For16 = new WinFormsField("FOR-16", "For16");
        public static WinFormsField Against16 = new WinFormsField("AGAINST-16", "Against16");
        public static WinFormsField OpenTicked16 = new WinFormsField("OPEN-TICKED-16", "OpenTicked16");
        public static WinFormsField OpenUnticked16 = new WinFormsField("OPEN-UNTICKED-16", "OpenUnticked16");
        public static WinFormsField Abstain16 = new WinFormsField("ABSTAIN-16", "Abstain16");
        public static WinFormsField Exclude16 = new WinFormsField("EXCLUDE-16", "Exclude16");
        public static WinFormsField For17 = new WinFormsField("FOR-17", "For17");
        public static WinFormsField Against17 = new WinFormsField("AGAINST-17", "Against17");
        public static WinFormsField OpenTicked17 = new WinFormsField("OPEN-TICKED-17", "OpenTicked17");
        public static WinFormsField OpenUnticked17 = new WinFormsField("OPEN-UNTICKED-17", "OpenUnticked17");
        public static WinFormsField Abstain17 = new WinFormsField("ABSTAIN-17", "Abstain17");
        public static WinFormsField Exclude17 = new WinFormsField("EXCLUDE-17", "Exclude17");
        public static WinFormsField For18 = new WinFormsField("FOR-18", "For18");
        public static WinFormsField Against18 = new WinFormsField("AGAINST-18", "Against18");
        public static WinFormsField OpenTicked18 = new WinFormsField("OPEN-TICKED-18", "OpenTicked18");
        public static WinFormsField OpenUnticked18 = new WinFormsField("OPEN-UNTICKED-18", "OpenUnticked18");
        public static WinFormsField Abstain18 = new WinFormsField("ABSTAIN-18", "Abstain18");
        public static WinFormsField Exclude18 = new WinFormsField("EXCLUDE-18", "Exclude18");
        public static WinFormsField For19 = new WinFormsField("FOR-19", "For19");
        public static WinFormsField Against19 = new WinFormsField("AGAINST-19", "Against19");
        public static WinFormsField OpenTicked19 = new WinFormsField("OPEN-TICKED-19", "OpenTicked19");
        public static WinFormsField OpenUnticked19 = new WinFormsField("OPEN-UNTICKED-19", "OpenUnticked19");
        public static WinFormsField Abstain19 = new WinFormsField("ABSTAIN-19", "Abstain19");
        public static WinFormsField Exclude19 = new WinFormsField("EXCLUDE-19", "Exclude19");
        public static WinFormsField For20 = new WinFormsField("FOR-20", "For20");
        public static WinFormsField Against20 = new WinFormsField("AGAINST-20", "Against20");
        public static WinFormsField OpenTicked20 = new WinFormsField("OPEN-TICKED-20", "OpenTicked20");
        public static WinFormsField OpenUnticked20 = new WinFormsField("OPEN-UNTICKED-20", "OpenUnticked20");
        public static WinFormsField Abstain20 = new WinFormsField("ABSTAIN-20", "Abstain20");
        public static WinFormsField Exclude20 = new WinFormsField("EXCLUDE-20", "Exclude20");
        public static WinFormsField SystemInfoFree6 = new WinFormsField("SYSTEM-INFO-FREE-6", "20", "20");
        public static WinFormsField SystemInfoFree4 = new WinFormsField("SYSTEM-INFO-FREE-4", "18", "18");
        public static WinFormsField SystemInfoFree7 = new WinFormsField("SYSTEM-INFO-FREE-7", "21", "21");
    }
}
