using System;
using TechTalk.SpecFlow;
using Spartan.Core.WinForms.WinFormsObjects;
using Spartan.Core.WinForms;
using Spartan.Core;

namespace SCRIPAU.Automation.Screens
{
    [Binding]
    public class SEYT0106

    {
		//Form Object
		public static WinFormsForm FormName = new WinFormsForm("SEYT0106", "FormName");
		//Fields


        public static WinFormsField FinYear = new WinFormsField("FIN-YEAR", "FinYear");
        public static WinFormsField FinYearDesc = new WinFormsField("FIN-YEAR-DESC", "FinYearDesc");
        public static WinFormsField SelectGrp = new WinFormsField("SELECT-GRP", "SelectGrp");
        public static WinFormsField PaymentType = new WinFormsField("PAYMENT-TYPE", "PaymentType");
        public static WinFormsField CO = new WinFormsField("CO", "CO");
        public static WinFormsField Pe1 = new WinFormsField("PE1", "Pe1");
        public static WinFormsField Rnx1 = new WinFormsField("RNX1", "Rnx1");
        public static WinFormsField Re1 = new WinFormsField("RE1", "Re1");
        public static WinFormsField Rt1 = new WinFormsField("RT1", "Rt1");
        public static WinFormsField Gr1 = new WinFormsField("GR1", "Gr1");
        public static WinFormsField Ig1 = new WinFormsField("IG1", "Ig1");
        public static WinFormsField Sq1 = new WinFormsField("SQ1", "Sq1");
        public static WinFormsField Ta1 = new WinFormsField("TA1", "Ta1");
        public static WinFormsField Fp1 = new WinFormsField("FP1", "Fp1");
        public static WinFormsField Desc = new WinFormsField("DESC", "Desc");
        public static WinFormsField Pe2 = new WinFormsField("PE2", "Pe2");
        public static WinFormsField Rnx2 = new WinFormsField("RNX2", "Rnx2");
        public static WinFormsField Re2 = new WinFormsField("RE2", "Re2");
        public static WinFormsField Rt2 = new WinFormsField("RT2", "Rt2");
        public static WinFormsField Gr2 = new WinFormsField("GR2", "Gr2");
        public static WinFormsField Ig2 = new WinFormsField("IG2", "Ig2");
        public static WinFormsField Sq2 = new WinFormsField("SQ2", "Sq2");
        public static WinFormsField Ta2 = new WinFormsField("TA2", "Ta2");
        public static WinFormsField Fp2 = new WinFormsField("FP2", "Fp2");
        public static WinFormsField Pe3 = new WinFormsField("PE3", "Pe3");
        public static WinFormsField Rnx3 = new WinFormsField("RNX3", "Rnx3");
        public static WinFormsField Re3 = new WinFormsField("RE3", "Re3");
        public static WinFormsField Rt3 = new WinFormsField("RT3", "Rt3");
        public static WinFormsField Gr3 = new WinFormsField("GR3", "Gr3");
        public static WinFormsField Ig3 = new WinFormsField("IG3", "Ig3");
        public static WinFormsField Sq3 = new WinFormsField("SQ3", "Sq3");
        public static WinFormsField Ta3 = new WinFormsField("TA3", "Ta3");
        public static WinFormsField Fp3 = new WinFormsField("FP3", "Fp3");
        public static WinFormsField Pe4 = new WinFormsField("PE4", "Pe4");
        public static WinFormsField Rnx4 = new WinFormsField("RNX4", "Rnx4");
        public static WinFormsField Re4 = new WinFormsField("RE4", "Re4");
        public static WinFormsField Rt4 = new WinFormsField("RT4", "Rt4");
        public static WinFormsField Gr4 = new WinFormsField("GR4", "Gr4");
        public static WinFormsField Ig4 = new WinFormsField("IG4", "Ig4");
        public static WinFormsField Sq4 = new WinFormsField("SQ4", "Sq4");
        public static WinFormsField Ta4 = new WinFormsField("TA4", "Ta4");
        public static WinFormsField Fp4 = new WinFormsField("FP4", "Fp4");
        public static WinFormsField Pe5 = new WinFormsField("PE5", "Pe5");
        public static WinFormsField Rnx5 = new WinFormsField("RNX5", "Rnx5");
        public static WinFormsField Re5 = new WinFormsField("RE5", "Re5");
        public static WinFormsField Rt5 = new WinFormsField("RT5", "Rt5");
        public static WinFormsField Gr5 = new WinFormsField("GR5", "Gr5");
        public static WinFormsField Ig5 = new WinFormsField("IG5", "Ig5");
        public static WinFormsField Sq5 = new WinFormsField("SQ5", "Sq5");
        public static WinFormsField Ta5 = new WinFormsField("TA5", "Ta5");
        public static WinFormsField Fp5 = new WinFormsField("FP5", "Fp5");
        public static WinFormsField Pe6 = new WinFormsField("PE6", "Pe6");
        public static WinFormsField Rnx6 = new WinFormsField("RNX6", "Rnx6");
        public static WinFormsField Re6 = new WinFormsField("RE6", "Re6");
        public static WinFormsField Rt6 = new WinFormsField("RT6", "Rt6");
        public static WinFormsField Gr6 = new WinFormsField("GR6", "Gr6");
        public static WinFormsField Ig6 = new WinFormsField("IG6", "Ig6");
        public static WinFormsField Sq6 = new WinFormsField("SQ6", "Sq6");
        public static WinFormsField Ta6 = new WinFormsField("TA6", "Ta6");
        public static WinFormsField Fp6 = new WinFormsField("FP6", "Fp6");
        public static WinFormsField Pe7 = new WinFormsField("PE7", "Pe7");
        public static WinFormsField Rnx7 = new WinFormsField("RNX7", "Rnx7");
        public static WinFormsField Re7 = new WinFormsField("RE7", "Re7");
        public static WinFormsField Rt7 = new WinFormsField("RT7", "Rt7");
        public static WinFormsField Gr7 = new WinFormsField("GR7", "Gr7");
        public static WinFormsField Ig7 = new WinFormsField("IG7", "Ig7");
        public static WinFormsField Sq7 = new WinFormsField("SQ7", "Sq7");
        public static WinFormsField Ta7 = new WinFormsField("TA7", "Ta7");
        public static WinFormsField Fp7 = new WinFormsField("FP7", "Fp7");
        public static WinFormsField Pe8 = new WinFormsField("PE8", "Pe8");
        public static WinFormsField Rnx8 = new WinFormsField("RNX8", "Rnx8");
        public static WinFormsField Re8 = new WinFormsField("RE8", "Re8");
        public static WinFormsField Rt8 = new WinFormsField("RT8", "Rt8");
        public static WinFormsField Gr8 = new WinFormsField("GR8", "Gr8");
        public static WinFormsField Ig8 = new WinFormsField("IG8", "Ig8");
        public static WinFormsField Sq8 = new WinFormsField("SQ8", "Sq8");
        public static WinFormsField Ta8 = new WinFormsField("TA8", "Ta8");
        public static WinFormsField Fp8 = new WinFormsField("FP8", "Fp8");
        public static WinFormsField Pe9 = new WinFormsField("PE9", "Pe9");
        public static WinFormsField Rnx9 = new WinFormsField("RNX9", "Rnx9");
        public static WinFormsField Re9 = new WinFormsField("RE9", "Re9");
        public static WinFormsField Rt9 = new WinFormsField("RT9", "Rt9");
        public static WinFormsField Gr9 = new WinFormsField("GR9", "Gr9");
        public static WinFormsField Ig9 = new WinFormsField("IG9", "Ig9");
        public static WinFormsField Sq9 = new WinFormsField("SQ9", "Sq9");
        public static WinFormsField Ta9 = new WinFormsField("TA9", "Ta9");
        public static WinFormsField Fp9 = new WinFormsField("FP9", "Fp9");
        public static WinFormsField Pe10 = new WinFormsField("PE10", "Pe10");
        public static WinFormsField Rnx10 = new WinFormsField("RNX10", "Rnx10");
        public static WinFormsField Re10 = new WinFormsField("RE10", "Re10");
        public static WinFormsField Rt10 = new WinFormsField("RT10", "Rt10");
        public static WinFormsField Gr10 = new WinFormsField("GR10", "Gr10");
        public static WinFormsField Ig10 = new WinFormsField("IG10", "Ig10");
        public static WinFormsField Sq10 = new WinFormsField("SQ10", "Sq10");
        public static WinFormsField Ta10 = new WinFormsField("TA10", "Ta10");
        public static WinFormsField Fp10 = new WinFormsField("FP10", "Fp10");
        public static WinFormsField Pe11 = new WinFormsField("PE11", "Pe11");
        public static WinFormsField Rnx11 = new WinFormsField("RNX11", "Rnx11");
        public static WinFormsField Re11 = new WinFormsField("RE11", "Re11");
        public static WinFormsField Rt11 = new WinFormsField("RT11", "Rt11");
        public static WinFormsField Gr11 = new WinFormsField("GR11", "Gr11");
        public static WinFormsField Ig11 = new WinFormsField("IG11", "Ig11");
        public static WinFormsField Sq11 = new WinFormsField("SQ11", "Sq11");
        public static WinFormsField Ta11 = new WinFormsField("TA11", "Ta11");
        public static WinFormsField Fp11 = new WinFormsField("FP11", "Fp11");
        public static WinFormsField Pe12 = new WinFormsField("PE12", "Pe12");
        public static WinFormsField Rnx12 = new WinFormsField("RNX12", "Rnx12");
        public static WinFormsField Re12 = new WinFormsField("RE12", "Re12");
        public static WinFormsField Rt12 = new WinFormsField("RT12", "Rt12");
        public static WinFormsField Gr12 = new WinFormsField("GR12", "Gr12");
        public static WinFormsField Ig12 = new WinFormsField("IG12", "Ig12");
        public static WinFormsField Sq12 = new WinFormsField("SQ12", "Sq12");
        public static WinFormsField Ta12 = new WinFormsField("TA12", "Ta12");
        public static WinFormsField Fp12 = new WinFormsField("FP12", "Fp12");
        public static WinFormsField Pe13 = new WinFormsField("PE13", "Pe13");
        public static WinFormsField Rnx13 = new WinFormsField("RNX13", "Rnx13");
        public static WinFormsField Re13 = new WinFormsField("RE13", "Re13");
        public static WinFormsField Rt13 = new WinFormsField("RT13", "Rt13");
        public static WinFormsField Gr13 = new WinFormsField("GR13", "Gr13");
        public static WinFormsField Ig13 = new WinFormsField("IG13", "Ig13");
        public static WinFormsField Sq13 = new WinFormsField("SQ13", "Sq13");
        public static WinFormsField Ta13 = new WinFormsField("TA13", "Ta13");
        public static WinFormsField Fp13 = new WinFormsField("FP13", "Fp13");
        public static WinFormsField Pe14 = new WinFormsField("PE14", "Pe14");
        public static WinFormsField Rnx14 = new WinFormsField("RNX14", "Rnx14");
        public static WinFormsField Re14 = new WinFormsField("RE14", "Re14");
        public static WinFormsField Rt14 = new WinFormsField("RT14", "Rt14");
        public static WinFormsField Gr14 = new WinFormsField("GR14", "Gr14");
        public static WinFormsField Ig14 = new WinFormsField("IG14", "Ig14");
        public static WinFormsField Sq14 = new WinFormsField("SQ14", "Sq14");
        public static WinFormsField Ta14 = new WinFormsField("TA14", "Ta14");
        public static WinFormsField Fp14 = new WinFormsField("FP14", "Fp14");
        public static WinFormsField Pe15 = new WinFormsField("PE15", "Pe15");
        public static WinFormsField Rnx15 = new WinFormsField("RNX15", "Rnx15");
        public static WinFormsField Re15 = new WinFormsField("RE15", "Re15");
        public static WinFormsField Rt15 = new WinFormsField("RT15", "Rt15");
        public static WinFormsField Gr15 = new WinFormsField("GR15", "Gr15");
        public static WinFormsField Ig15 = new WinFormsField("IG15", "Ig15");
        public static WinFormsField Sq15 = new WinFormsField("SQ15", "Sq15");
        public static WinFormsField Ta15 = new WinFormsField("TA15", "Ta15");
        public static WinFormsField Fp15 = new WinFormsField("FP15", "Fp15");
        public static WinFormsField Filler = new WinFormsField("FILLER", "Filler");
        public static WinFormsField SystemInfoFree6 = new WinFormsField("SYSTEM-INFO-FREE-6", "20", "20");
        public static WinFormsField SystemInfoFree4 = new WinFormsField("SYSTEM-INFO-FREE-4", "18", "18");
        public static WinFormsField SystemInfoFree7 = new WinFormsField("SYSTEM-INFO-FREE-7", "21", "21");
        public static WinFormsField SystemInfoFree5 = new WinFormsField("SYSTEM-INFO-FREE-5", "19", "19");
    }
}
