// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SCRIPAU.Automation.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("EN_E_CompanyOptions")]
    public partial class EN_E_CompanyOptionsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EN_E_CompanyOptions.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EN_E_CompanyOptions", "Ensure EN_E_CompanyOptions functionality covered", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18423: 01_Sub Systems (CCO Action)")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("CPU_AUTO")]
        [NUnit.Framework.CategoryAttribute("18423")]
        [NUnit.Framework.CategoryAttribute("EN_E_CompanyOptions")]
        public virtual void TestCase1842301_SubSystemsCCOAction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18423: 01_Sub Systems (CCO Action)", new string[] {
                        "winformsTest",
                        "EnquiryTest",
                        "CPU_AUTO",
                        "18423",
                        "EN_E_CompanyOptions"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 11
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
 testRunner.When("In SELCOY01 I select the company: \"CPU_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
  testRunner.And("I go to Holder Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "Action",
                        "CCO"});
            table1.AddRow(new string[] {
                        "Locate Argument",
                        ""});
#line 14
  testRunner.And("I enter the following details as the Locate action:", ((string)(null)), table1, "And ");
#line 18
 testRunner.Then("I expect to be in the \"HCC00101\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
 testRunner.When("In HCC00101 I enter the selection as \"CTL\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.Then("I expect to be in the \"HCC00102\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
 testRunner.When("I PressESC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.Then("I expect to be in the \"HCC00101\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
 testRunner.When("In HCC00101 I enter the selection as \"DC\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
 testRunner.Then("I expect to be in the \"HCC00103\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 25
 testRunner.When("I PressESC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
  testRunner.And("I PressESC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.Then("I expect to be in the \"ENS01090\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18425: 03_Sub Systems (BLK) - Bulk Transaction List")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("CPU_AUTO")]
        [NUnit.Framework.CategoryAttribute("18425")]
        [NUnit.Framework.CategoryAttribute("EN_E_CompanyOptions")]
        public virtual void TestCase1842503_SubSystemsBLK_BulkTransactionList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18425: 03_Sub Systems (BLK) - Bulk Transaction List", new string[] {
                        "winformsTest",
                        "EnquiryTest",
                        "CPU_AUTO",
                        "18425",
                        "EN_E_CompanyOptions"});
#line 34
this.ScenarioSetup(scenarioInfo);
#line 36
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
 testRunner.When("In SELCOY01 I select the company: \"CPU_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
  testRunner.And("I go to Holder Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "Action",
                        "BLK"});
            table2.AddRow(new string[] {
                        "Locate Argument",
                        ""});
#line 39
  testRunner.And("I enter the following details as the Locate action:", ((string)(null)), table2, "And ");
#line 43
 testRunner.Then("I expect to be in the \"OLSBLK01\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 44
 testRunner.When("In OLSBLK01 I enter the selection as \"97B\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
 testRunner.Then("I expect to be in the \"OLSBLK02\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 46
 testRunner.When("In OLSBLK02 I enter the selection as \"BTL\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
 testRunner.Then("I expect to be in the \"OLSB0601\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 48
 testRunner.When("I Transmit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then("I expect to be in the \"OLSB0603\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 50
 testRunner.When("I Transmit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 51
 testRunner.Then("I expect to be in the \"OLSB0604\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 52
 testRunner.When("I PressESC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 53
 testRunner.Then("I expect to be in the \"OLSBLK01\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18455: 04_Sub Systems (BLK) - Bulk Transaction Enquiry")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("ANZ_AUTO")]
        [NUnit.Framework.CategoryAttribute("18455")]
        [NUnit.Framework.CategoryAttribute("EN_E_CompanyOptions")]
        public virtual void TestCase1845504_SubSystemsBLK_BulkTransactionEnquiry()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18455: 04_Sub Systems (BLK) - Bulk Transaction Enquiry", new string[] {
                        "winformsTest",
                        "EnquiryTest",
                        "ANZ_AUTO",
                        "18455",
                        "EN_E_CompanyOptions"});
#line 60
this.ScenarioSetup(scenarioInfo);
#line 62
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 63
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
  testRunner.And("I go to Holder Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "Action",
                        "BLK"});
            table3.AddRow(new string[] {
                        "Locate Argument",
                        ""});
#line 65
  testRunner.And("I enter the following details as the Locate action:", ((string)(null)), table3, "And ");
#line 69
 testRunner.Then("I expect to be in the \"OLSBLK01\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 70
 testRunner.When("In OLSBLK01 I enter the selection as \"DEF\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 71
 testRunner.Then("I expect to be in the \"OLSBLK02\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 72
 testRunner.When("In OLSBLK02 I enter the selection as \"BTQ\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 73
 testRunner.Then("I expect to be in the \"BLKSCH01\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 74
 testRunner.When("In BLKSCH01 I enter the selection as \"DEF0000794\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 75
 testRunner.Then("I expect to be in the \"OLSB1010\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "Action",
                        "M"});
            table4.AddRow(new string[] {
                        "TranNo",
                        ""});
#line 76
 testRunner.When("In OLSB1010 I enter the Action details as below:", ((string)(null)), table4, "When ");
#line 80
 testRunner.Then("I expect to be in the \"OLSB1020\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 81
 testRunner.When("I PressESC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 82
 testRunner.Then("I expect to be in the \"OLSB1010\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "Action",
                        "S"});
            table5.AddRow(new string[] {
                        "TranNo",
                        "578588"});
#line 83
 testRunner.When("In OLSB1010 I enter the Action details as below:", ((string)(null)), table5, "When ");
#line 87
 testRunner.Then("I expect to be in the \"OLSB1010\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table6.AddRow(new string[] {
                        "Action",
                        "B"});
            table6.AddRow(new string[] {
                        "TranNo",
                        ""});
#line 88
 testRunner.When("In OLSB1010 I enter the Action details as below:", ((string)(null)), table6, "When ");
#line 92
 testRunner.Then("I expect to be in the \"OLSB1010\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table7.AddRow(new string[] {
                        "Action",
                        "F"});
            table7.AddRow(new string[] {
                        "TranNo",
                        ""});
#line 93
 testRunner.When("In OLSB1010 I enter the Action details as below:", ((string)(null)), table7, "When ");
#line 97
 testRunner.Then("I expect to be in the \"OLSB1010\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 98
 testRunner.When("I PressESC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 99
  testRunner.And("I PressESC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
 testRunner.Then("I expect to be in the \"OLSBLK01\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 101
 testRunner.When("In OLSBLK01 I enter the selection as \"BFI\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 102
 testRunner.Then("I expect to be in the \"OLSBLK02\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 103
 testRunner.When("In OLSBLK02 I enter the selection as \"BTQ\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 104
 testRunner.Then("I expect to be in the \"BLKSCH01\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 105
 testRunner.When("In BLKSCH01 I enter the selection as \"BFI0001506\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 106
 testRunner.Then("I expect to be in the \"OLSB10T1\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18456: 05_Sub Systems (BLK) - Bulk Transaction Range Report")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("ANZ_AUTO")]
        [NUnit.Framework.CategoryAttribute("18456")]
        [NUnit.Framework.CategoryAttribute("EN_E_CompanyOptions")]
        public virtual void TestCase1845605_SubSystemsBLK_BulkTransactionRangeReport()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18456: 05_Sub Systems (BLK) - Bulk Transaction Range Report", new string[] {
                        "winformsTest",
                        "EnquiryTest",
                        "ANZ_AUTO",
                        "18456",
                        "EN_E_CompanyOptions"});
#line 113
this.ScenarioSetup(scenarioInfo);
#line 115
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 116
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 117
  testRunner.And("I go to Holder Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table8.AddRow(new string[] {
                        "Action",
                        "BLK"});
            table8.AddRow(new string[] {
                        "Locate Argument",
                        ""});
#line 118
  testRunner.And("I enter the following details as the Locate action:", ((string)(null)), table8, "And ");
#line 122
 testRunner.Then("I expect to be in the \"OLSBLK01\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 123
 testRunner.When("In OLSBLK01 I enter the selection as \"DEF\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 124
 testRunner.Then("I expect to be in the \"OLSBLK02\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 125
 testRunner.When("In OLSBLK02 I enter the selection as \"BTR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 126
 testRunner.Then("I expect to be in the \"BLKSCH01\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 127
 testRunner.When("In BLKSCH01 I enter the selection as \"DEF0001031\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 128
 testRunner.Then("I expect to be in the \"OLSB0701\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table9.AddRow(new string[] {
                        "SharePriceFrom",
                        "1"});
            table9.AddRow(new string[] {
                        "SharePriceTo",
                        "10"});
            table9.AddRow(new string[] {
                        "SharePriceInterval",
                        "1"});
            table9.AddRow(new string[] {
                        "MaxUnits",
                        "100"});
#line 129
 testRunner.When("In OLSB0701 I enter Bulk Transaction Report details as below:", ((string)(null)), table9, "When ");
#line 135
 testRunner.Then("I expect to be in the \"JOBSUB03\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table10.AddRow(new string[] {
                        "OrderNbr",
                        "3000"});
            table10.AddRow(new string[] {
                        "OperatorInitials",
                        "NDF"});
#line 136
 testRunner.When("In JOBSUB03 I enter Job Identification details as below:", ((string)(null)), table10, "When ");
#line 140
 testRunner.Then("I expect to be in the \"JOBSUB04\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 141
 testRunner.When("I Transmit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 142
 testRunner.Then("I expect to be in the \"JOBSUB05\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table11.AddRow(new string[] {
                        "PrintOption",
                        "N"});
#line 143
 testRunner.When("In JOBSUB05 I enter Output Options as below:", ((string)(null)), table11, "When ");
#line 146
 testRunner.Then("I expect to be in the \"JOBSUB90\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 147
 testRunner.When("I Transmit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 148
 testRunner.Then("I expect to be in the \"BLK00101\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18457: 06_Sub Systems (BLK) - Bulk Order Processing")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("ANZ_AUTO")]
        [NUnit.Framework.CategoryAttribute("18457")]
        [NUnit.Framework.CategoryAttribute("EN_E_CompanyOptions")]
        public virtual void TestCase1845706_SubSystemsBLK_BulkOrderProcessing()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18457: 06_Sub Systems (BLK) - Bulk Order Processing", new string[] {
                        "winformsTest",
                        "EnquiryTest",
                        "ANZ_AUTO",
                        "18457",
                        "EN_E_CompanyOptions"});
#line 155
this.ScenarioSetup(scenarioInfo);
#line 157
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 158
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 159
  testRunner.And("I go to Holder Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table12.AddRow(new string[] {
                        "Action",
                        "BLK"});
            table12.AddRow(new string[] {
                        "Locate Argument",
                        ""});
#line 160
  testRunner.And("I enter the following details as the Locate action:", ((string)(null)), table12, "And ");
#line 164
 testRunner.Then("I expect to be in the \"OLSBLK01\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 165
 testRunner.When("In OLSBLK01 I enter the selection as \"DEF\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 166
 testRunner.Then("I expect to be in the \"OLSBLK02\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 167
 testRunner.When("In OLSBLK02 I enter the selection as \"BPE\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 168
 testRunner.Then("I expect to be in the \"BLKSCH01\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 169
 testRunner.When("In BLKSCH01 I enter the selection as \"DEF0001018\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 170
 testRunner.Then("I expect to be in the \"BLKSCH02\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 171
 testRunner.When("In BLKSCH02 I enter the selection as \"M\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 172
 testRunner.Then("I expect to be in the \"BLKSCH03\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 173
 testRunner.When("I PressESC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 174
  testRunner.And("I PressESC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 175
 testRunner.Then("I expect to be in the \"OLSBLK02\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18458: 07_Sub Systems (BLK) - Bulk Reporting Options")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("ANZ_AUTO")]
        [NUnit.Framework.CategoryAttribute("18458")]
        [NUnit.Framework.CategoryAttribute("EN_E_CompanyOptions")]
        public virtual void TestCase1845807_SubSystemsBLK_BulkReportingOptions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18458: 07_Sub Systems (BLK) - Bulk Reporting Options", new string[] {
                        "winformsTest",
                        "EnquiryTest",
                        "ANZ_AUTO",
                        "18458",
                        "EN_E_CompanyOptions"});
#line 182
this.ScenarioSetup(scenarioInfo);
#line 184
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 185
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 186
  testRunner.And("I go to Holder Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table13.AddRow(new string[] {
                        "Action",
                        "BLK"});
            table13.AddRow(new string[] {
                        "Locate Argument",
                        ""});
#line 187
  testRunner.And("I enter the following details as the Locate action:", ((string)(null)), table13, "And ");
#line 191
 testRunner.Then("I expect to be in the \"OLSBLK01\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 192
 testRunner.When("In OLSBLK01 I enter the selection as \"BRO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 193
 testRunner.Then("I expect to be in the \"OLSB0602\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 194
 testRunner.When("In OLSB0602 I enter Report Type as \"S\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 195
 testRunner.Then("I expect to be in the \"OLSB0603\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table14.AddRow(new string[] {
                        "OrderNbr",
                        "3001"});
            table14.AddRow(new string[] {
                        "OperatorInitials",
                        "NDF"});
#line 196
 testRunner.When("In JOBSUB03 I enter Job Identification details as below:", ((string)(null)), table14, "When ");
#line 200
 testRunner.Then("I expect to be in the \"OLSB0604\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
