// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SCRIPAU.Automation.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("EN_PE_PaymentEnquirySystem")]
    public partial class EN_PE_PaymentEnquirySystemFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EN_PE_PaymentEnquirySystem.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EN_PE_PaymentEnquirySystem", "Ensure EN_PE_PaymentEnquirySystem functionality covered", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18380: 01_Payment Enquiry System (PE Action)")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("CPU_AUTO")]
        [NUnit.Framework.CategoryAttribute("EN_PE_PaymentEnquirySystem")]
        [NUnit.Framework.CategoryAttribute("18380")]
        [NUnit.Framework.CategoryAttribute("FullSmokeTest")]
        public virtual void TestCase1838001_PaymentEnquirySystemPEAction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18380: 01_Payment Enquiry System (PE Action)", new string[] {
                        "winformsTest",
                        "EnquiryTest",
                        "CPU_AUTO",
                        "EN_PE_PaymentEnquirySystem",
                        "18380",
                        "FullSmokeTest"});
#line 10
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
 testRunner.When("In SELCOY01 I select the company: \"CPU_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
  testRunner.And("I go to Payment Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "Action",
                        "S"});
            table1.AddRow(new string[] {
                        "Locate Argument",
                        "06FIN"});
#line 15
  testRunner.And("I enter the following details in Payment Enquiry as the Locate action:", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "PaymentAccountNbr",
                        "06FIN"});
            table2.AddRow(new string[] {
                        "PaymentDesc",
                        "06 FINAL DIV 7C UNFRANK RD8/9 PD 22/9/06"});
            table2.AddRow(new string[] {
                        "OriginalGrossAmount",
                        "39285045.52"});
            table2.AddRow(new string[] {
                        "OriginalNettAmount",
                        "39109408.52"});
            table2.AddRow(new string[] {
                        "LowReferenceNbr",
                        "160448"});
            table2.AddRow(new string[] {
                        "HighReferenceNbr",
                        "90160450"});
            table2.AddRow(new string[] {
                        "NbrChqPresented",
                        "3"});
            table2.AddRow(new string[] {
                        "NbrChqCancelled",
                        "4"});
            table2.AddRow(new string[] {
                        "NbrDcPresented",
                        "573"});
            table2.AddRow(new string[] {
                        "NbrDcUnissued",
                        ""});
            table2.AddRow(new string[] {
                        "NbrDcCancelled",
                        "2"});
            table2.AddRow(new string[] {
                        "NbrTotalPresented",
                        "576"});
            table2.AddRow(new string[] {
                        "NbrTotalUnissued",
                        ""});
            table2.AddRow(new string[] {
                        "NbrTotalCancelled",
                        "6"});
            table2.AddRow(new string[] {
                        "NettChqPresented",
                        "1987.18"});
            table2.AddRow(new string[] {
                        "NettChqCancelled",
                        "555300.99"});
            table2.AddRow(new string[] {
                        "NettDcPresented",
                        "9054923.04"});
            table2.AddRow(new string[] {
                        "NettDcUnissued",
                        ""});
            table2.AddRow(new string[] {
                        "NettDcCancelled",
                        "27019.77"});
            table2.AddRow(new string[] {
                        "NettTotalPresented",
                        "9056910.22"});
            table2.AddRow(new string[] {
                        "NettTotalUnissued",
                        ""});
            table2.AddRow(new string[] {
                        "NettTotalCancelled",
                        "582320.76"});
#line 19
 testRunner.Then("In ENS02001 I should see Payment Enquiry details as below:", ((string)(null)), table2, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "Action",
                        "F"});
            table3.AddRow(new string[] {
                        "Locate Argument",
                        ""});
#line 43
 testRunner.When("I enter the following details in Payment Enquiry as the Locate action:", ((string)(null)), table3, "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "PaymentAccountNbr",
                        "06FIN"});
            table4.AddRow(new string[] {
                        "PaymentDesc",
                        "06 FINAL DIV 7C UNFRANK RD8/9 PD 22/9/06"});
            table4.AddRow(new string[] {
                        "OriginalGrossAmount",
                        "39285045.52"});
            table4.AddRow(new string[] {
                        "OriginalNettAmount",
                        "39109408.52"});
            table4.AddRow(new string[] {
                        "LowReferenceNbr",
                        "160448"});
            table4.AddRow(new string[] {
                        "HighReferenceNbr",
                        "90160450"});
            table4.AddRow(new string[] {
                        "NbrChqPresented",
                        ""});
            table4.AddRow(new string[] {
                        "NbrChqCancelled",
                        ""});
            table4.AddRow(new string[] {
                        "NbrDcPresented",
                        "10"});
            table4.AddRow(new string[] {
                        "NbrDcUnissued",
                        ""});
            table4.AddRow(new string[] {
                        "NbrDcCancelled",
                        ""});
            table4.AddRow(new string[] {
                        "NbrTotalPresented",
                        "10"});
            table4.AddRow(new string[] {
                        "NbrTotalUnissued",
                        ""});
            table4.AddRow(new string[] {
                        "NbrTotalCancelled",
                        ""});
            table4.AddRow(new string[] {
                        "NettChqPresented",
                        ""});
            table4.AddRow(new string[] {
                        "NettChqCancelled",
                        ""});
            table4.AddRow(new string[] {
                        "NettDcPresented",
                        "788.77"});
            table4.AddRow(new string[] {
                        "NettDcUnissued",
                        ""});
            table4.AddRow(new string[] {
                        "NettDcCancelled",
                        ""});
            table4.AddRow(new string[] {
                        "NettTotalPresented",
                        "788.77"});
            table4.AddRow(new string[] {
                        "NettTotalUnissued",
                        ""});
            table4.AddRow(new string[] {
                        "NettTotalCancelled",
                        ""});
#line 47
 testRunner.Then("In ENS02001 I should see Payment Enquiry details as below:", ((string)(null)), table4, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "Action",
                        "B"});
            table5.AddRow(new string[] {
                        "Locate Argument",
                        ""});
#line 71
 testRunner.When("I enter the following details in Payment Enquiry as the Locate action:", ((string)(null)), table5, "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table6.AddRow(new string[] {
                        "PaymentAccountNbr",
                        "06FDE"});
            table6.AddRow(new string[] {
                        "PaymentDesc",
                        "EMP DIV DEP/EXA 7C UF RD 8/09 PD 22/9/06"});
            table6.AddRow(new string[] {
                        "OriginalGrossAmount",
                        "148659.77"});
            table6.AddRow(new string[] {
                        "OriginalNettAmount",
                        "145466.77"});
            table6.AddRow(new string[] {
                        "LowReferenceNbr",
                        "160461"});
            table6.AddRow(new string[] {
                        "HighReferenceNbr",
                        "160822"});
            table6.AddRow(new string[] {
                        "NbrChqPresented",
                        ""});
            table6.AddRow(new string[] {
                        "NbrChqCancelled",
                        ""});
            table6.AddRow(new string[] {
                        "NbrDcPresented",
                        "146"});
            table6.AddRow(new string[] {
                        "NbrDcUnissued",
                        ""});
            table6.AddRow(new string[] {
                        "NbrDcCancelled",
                        ""});
            table6.AddRow(new string[] {
                        "NbrTotalPresented",
                        "146"});
            table6.AddRow(new string[] {
                        "NbrTotalUnissued",
                        ""});
            table6.AddRow(new string[] {
                        "NbrTotalCancelled",
                        ""});
            table6.AddRow(new string[] {
                        "NettChqPresented",
                        ""});
            table6.AddRow(new string[] {
                        "NettChqCancelled",
                        "3193.00"});
            table6.AddRow(new string[] {
                        "NettDcPresented",
                        "44687.89"});
            table6.AddRow(new string[] {
                        "NettDcUnissued",
                        ""});
            table6.AddRow(new string[] {
                        "NettDcCancelled",
                        ""});
            table6.AddRow(new string[] {
                        "NettTotalPresented",
                        "44687.89"});
            table6.AddRow(new string[] {
                        "NettTotalUnissued",
                        ""});
            table6.AddRow(new string[] {
                        "NettTotalCancelled",
                        "3193.00"});
#line 75
 testRunner.Then("In ENS02001 I should see Payment Enquiry details as below:", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18384: 03_Payment Enquiry System (PE) - Dual Currency -test1")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("CPU_AUTO")]
        [NUnit.Framework.CategoryAttribute("EN_PE_PaymentEnquirySystem")]
        [NUnit.Framework.CategoryAttribute("18384")]
        public virtual void TestCase1838403_PaymentEnquirySystemPE_DualCurrency_Test1()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18384: 03_Payment Enquiry System (PE) - Dual Currency -test1", new string[] {
                        "winformsTest",
                        "EnquiryTest",
                        "CPU_AUTO",
                        "EN_PE_PaymentEnquirySystem",
                        "18384"});
#line 105
this.ScenarioSetup(scenarioInfo);
#line 107
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 108
 testRunner.When("In SELCOY01 I select the company: \"CPU_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 109
  testRunner.And("I go to Payment Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table7.AddRow(new string[] {
                        "Action",
                        "S"});
            table7.AddRow(new string[] {
                        "Locate Argument",
                        "03FNZ"});
#line 110
  testRunner.And("I enter the following details in Payment Enquiry as the Locate action:", ((string)(null)), table7, "And ");
#line 114
 testRunner.Then("I expect to be in the \"ENS02001\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table8.AddRow(new string[] {
                        "Action",
                        "D"});
            table8.AddRow(new string[] {
                        "Locate Argument",
                        ""});
#line 115
 testRunner.When("I enter the following details in Payment Enquiry as the Locate action:", ((string)(null)), table8, "When ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table9.AddRow(new string[] {
                        "DualDcPresented",
                        "21279.15"});
            table9.AddRow(new string[] {
                        "DualDcCancelled",
                        "875.47"});
            table9.AddRow(new string[] {
                        "TotalDualPresented",
                        "21279.15"});
            table9.AddRow(new string[] {
                        "TotalDualCancelled",
                        "875.47"});
#line 119
 testRunner.Then("In ENS02002 I should see Dual Currency amounts as below:", ((string)(null)), table9, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18384: 03_Payment Enquiry System (PE) - Dual Currency -test2")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("CPU_AUTO")]
        [NUnit.Framework.CategoryAttribute("EN_PE_PaymentEnquirySystem")]
        [NUnit.Framework.CategoryAttribute("18384")]
        public virtual void TestCase1838403_PaymentEnquirySystemPE_DualCurrency_Test2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18384: 03_Payment Enquiry System (PE) - Dual Currency -test2", new string[] {
                        "winformsTest",
                        "EnquiryTest",
                        "CPU_AUTO",
                        "EN_PE_PaymentEnquirySystem",
                        "18384"});
#line 131
this.ScenarioSetup(scenarioInfo);
#line 133
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 134
 testRunner.When("In SELCOY01 I select the company: \"CPU_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 135
  testRunner.And("I go to Payment Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table10.AddRow(new string[] {
                        "Action",
                        "S"});
            table10.AddRow(new string[] {
                        "Locate Argument",
                        "06FIN"});
#line 136
  testRunner.And("I enter the following details in Payment Enquiry as the Locate action:", ((string)(null)), table10, "And ");
#line 140
 testRunner.Then("I expect to be in the \"ENS02001\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table11.AddRow(new string[] {
                        "Action",
                        "D"});
            table11.AddRow(new string[] {
                        "Locate Argument",
                        ""});
#line 141
 testRunner.When("I enter the following details in Payment Enquiry as the Locate action:", ((string)(null)), table11, "When ");
#line 145
 testRunner.Then("I expect to see error with text \"This account has NO dual currency.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18488: 03_Payment Enquiry System (PE) - Dual Currency - Error Message")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("CPU_AUTO")]
        [NUnit.Framework.CategoryAttribute("EN_PE_PaymentEnquirySystem")]
        [NUnit.Framework.CategoryAttribute("18488")]
        public virtual void TestCase1848803_PaymentEnquirySystemPE_DualCurrency_ErrorMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18488: 03_Payment Enquiry System (PE) - Dual Currency - Error Message", new string[] {
                        "winformsTest",
                        "EnquiryTest",
                        "CPU_AUTO",
                        "EN_PE_PaymentEnquirySystem",
                        "18488"});
#line 152
this.ScenarioSetup(scenarioInfo);
#line 154
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 155
 testRunner.When("In SELCOY01 I select the company: \"CPU_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 156
  testRunner.And("I go to Payment Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table12.AddRow(new string[] {
                        "Action",
                        "S"});
            table12.AddRow(new string[] {
                        "Locate Argument",
                        "X4VFR"});
#line 157
  testRunner.And("I enter the following details in Payment Enquiry as the Locate action:", ((string)(null)), table12, "And ");
#line 161
 testRunner.Then("I expect to see error with text \"The code you are searching for is not on file.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
