// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SCRIPAU.Automation.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("EN_SE_StatisticsEnquiry")]
    public partial class EN_SE_StatisticsEnquiryFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EN_SE_StatisticsEnquiry.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EN_SE_StatisticsEnquiry", "Ensure EN_SE_StatisticsEnquiry functionality covered", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18471: 01_Options on the Statistic Enquiries form")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("DIV_A")]
        [NUnit.Framework.CategoryAttribute("EN_SE_StatisticsEnquiry")]
        [NUnit.Framework.CategoryAttribute("18471")]
        [NUnit.Framework.TestCaseAttribute("ART", "Do not change ANYTHING - Thank you :)           (3400/3524)", "ANNUAL REPORT/RETURN MAIL TOTALS                   AS AT 26/03/10", "PUBLICATIONS TYPES               --POST- -EMAIL- --NONE- SC NOT- -TOTAL-", "PROVIDED", "COMPANY REPORTING", "A ANNUAL REPORT                    101       0      67    7668    7836", "B ANNUAL REPORT                    127       0       7   11067   11201", "N ANNUAL REPORT                      0       0    1073    8525    9598", "INVALID ANNUAL REPORT FLAGS          0       0       0       5       5", "TOTALS FOR PERIODIC REPORTING        228       0    1147   27265   28640", "NOT IN USE3                            0       0       0   28640   28640", "RETURN MAIL HOLDERS                  244", "WARNING: Report based on the following classes:..., *G9", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("DPID", "Do not change ANYTHING - Thank you :)           (3400/3524)", "DPID TOTALS REPORT                                 AS AT 26/03/10", "DPID ELIGIBLE    HOLDERS WITH DPID  HOLDERS WITH NO DPID", "CHESS                        20968                   93                 20875", "NON-CHESS                     5614                   29                  5585", "TOTAL-HOLDERS                26582                  122                 26460", "SUCCESS RATE:            0.45%", "DPID ELIGIBLE    HOLDERS WITH DPID  HOLDERS WITH NO DPID", "WARNING: Report based on the following classes:..., *G9", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("SBR", "Do not change ANYTHING - Thank you :)           (3400/3524)", "SECURITY HOLDERS BY REGISTER ACC/TOP UP ACCEPTANCE CLASS        AS AT 26/03/10", "REGISTER                  HOLDERS                    UNITS", "Issuer           NSW                             2                  40,000", "TOTAL                                            2                  40,000", "", "", "", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("T40", "Do not change ANYTHING - Thank you :)           (3400/3524)", "TOP   1 SECURITY HOLDERS *G9/ALL CLASSES                    AS AT 26/03/10", "NAME                             UNITS AS AT  VARIANCE UNITS AS AT % I/C RANK", "8/09/08              26/03/10", "*JP MORGAN NOMINEES AUSTRALIA         138460232          0  138460232  10.77   1", "*** REPORT TOTAL ***                 138460232             138460232  10.77", "***  DIFFERENCE  ***                1146832076            1147061580  89.23", "***        TOTAL ***                1285292308            1285521812 100.00", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("RS", "Do not change ANYTHING - Thank you :)           (3400/3524)", "RANGE OF SHARES *G9/ALL CLASSES                    AS AT 26/03/10", "RANGE            HOLDERS               UNITS         % I/C", "1 - 1000             3,538          2,231,473          0.17", "1001 - 5000            12,826         36,126,231          2.81", "5001 - 10000            6,114         45,627,898          3.55", "10001 - 100000           5,711        154,525,229         12.02", "100001 - OVER               451      1,047,010,981         81.45", "--------------------", "ROUNDING DISCREPANCY                                             0.00", "TOTAL                         28,640      1,285,521,812        100.00", "LESS THAN M/P OF       1           0                  0", "", "Cert         1 - 1000                 2                700          0.00", "1001 - 5000                 0                  0          0.00", "5001 - 10000                0                  0          0.00", "10001 - 100000               0                  0          0.00", "100001 - OVER                 0                  0          0.00", "", null)]
        [NUnit.Framework.TestCaseAttribute("SBD", "Do not change ANYTHING - Thank you :)           (3400/3524)", "SECURITY HOLDERS BY DOMICILE ACC/TOP UP ACCEPTANCE CLASS        AS AT 26/03/10", "DOMICILE                  HOLDERS                    UNITS", "VIC                             1                  20,000", "ARG ARGENTINA                   1                  20,000", "---------------------------", "LOCAL HOLDERS THIS CLASS            1                  20,000", "OVERSEAS HOLDERS THIS CLASS         1                  20,000", "CLASS TOTAL                         2                  40,000", "", "Issuer           VIC                             1                  20,000", "ARG ARGENTINA                   1                  20,000", "", "LOCAL HOLDERS SUB TOTAL             1                  20,000", "OVERSEAS HOLDERS SUB TOTAL          1                  20,000", "---------------------------", "LOCAL HOLDERS THIS CLASS            1                  20,000", "OVERSEAS HOLDERS THIS CLASS         1                  20,000", "CLASS TOTAL                         2                  40,000", null)]
        public virtual void TestCase1847101_OptionsOnTheStatisticEnquiriesForm(
                    string action, 
                    string line1, 
                    string line2, 
                    string line3, 
                    string line4, 
                    string line5, 
                    string line6, 
                    string line7, 
                    string line8, 
                    string line9, 
                    string line10, 
                    string line11, 
                    string line12, 
                    string line13, 
                    string line14, 
                    string line15, 
                    string line16, 
                    string line17, 
                    string line18, 
                    string line19, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "EnquiryTest",
                    "DIV_A",
                    "EN_SE_StatisticsEnquiry",
                    "18471"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18471: 01_Options on the Statistic Enquiries form", @__tags);
#line 9
this.ScenarioSetup(scenarioInfo);
#line 11
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
 testRunner.When("In SELCOY01 I select the company: \"DIV_A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
  testRunner.And("I go to Statistics Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
  testRunner.And(string.Format("In ENS04010 I Select Statistic Enquiry action as \"{0}\"", action), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.Then(string.Format("In ENS04020 I should see Statistics Enquiry details as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{" +
                        "4}\" \"{5}\" \"{6}\" \"{7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16" +
                        "}\" \"{17}\" \"{18}\"", line1, line2, line3, line4, line5, line6, line7, line8, line9, line10, line11, line12, line13, line14, line15, line16, line17, line18, line19), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18478: 02_Statistic Enquiries - Search by a Class Code")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("DIV_A")]
        [NUnit.Framework.CategoryAttribute("EN_SE_StatisticsEnquiry")]
        [NUnit.Framework.CategoryAttribute("18478")]
        [NUnit.Framework.TestCaseAttribute("CRT", "Do not change ANYTHING - Thank you :)           (3400/3524)", "CLASS REGISTER TOTALS ACC/TOP UP ACCEPTANCE CLASS        AS AT 26/03/10", "NIL      CURRENT", "REG  HOLDERS  HOLDERS  ---- UNITS ----", "Issuer        NSW         0         2           40,000", "TOTAL                     0         2           40,000", "CLASS HOLDER RECORDS                2", "F", "", "Do not change ANYTHING - Thank you :)           (3400/3524)", "CLASS REGISTER TOTALS DA1/FULLY PAID ORDINARY SHARES     AS AT 26/03/10", "NIL      CURRENT", "REG  HOLDERS  HOLDERS  ---- UNITS ----", "Issuer        NSW         0         2           20,000", "TOTAL                     0         2           20,000", "CLASS HOLDER RECORDS                2", "S", "ESC", "Do not change ANYTHING - Thank you :)           (3400/3524)", "CLASS REGISTER TOTALS ESC/ESCROW CLASS EXP TBA BY CLIENT AS AT 26/03/10", "NIL      CURRENT", "REG  HOLDERS  HOLDERS  ---- UNITS ----", "Issuer        NSW         1         1          203,730", "TOTAL                     1         1          203,730", "CLASS HOLDER RECORDS                2", null)]
        public virtual void TestCase1847802_StatisticEnquiries_SearchByAClassCode(
                    string action, 
                    string line1, 
                    string line2, 
                    string line3, 
                    string line4, 
                    string line5, 
                    string line6, 
                    string line7, 
                    string selection, 
                    string searchString, 
                    string line1Pg2, 
                    string line2Pg2, 
                    string line3Pg2, 
                    string line4Pg2, 
                    string line5Pg2, 
                    string line6Pg2, 
                    string line7Pg2, 
                    string selection1, 
                    string searchString1, 
                    string line1Pg3, 
                    string line2Pg3, 
                    string line3Pg3, 
                    string line4Pg3, 
                    string line5Pg3, 
                    string line6Pg3, 
                    string line7Pg3, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "EnquiryTest",
                    "DIV_A",
                    "EN_SE_StatisticsEnquiry",
                    "18478"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18478: 02_Statistic Enquiries - Search by a Class Code", @__tags);
#line 31
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 34
 testRunner.When("In SELCOY01 I select the company: \"DIV_A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
  testRunner.And("I go to Statistics Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
  testRunner.And(string.Format("In ENS04010 I Select Statistic Enquiry action as \"{0}\"", action), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.Then(string.Format("In ENS04020 I should see Class Statistics Enquiry details as \"{0}\" \"{1}\" \"{2}\" \"{" +
                        "3}\" \"{4}\" \"{5}\" \"{6}\"", line1, line2, line3, line4, line5, line6, line7), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 38
 testRunner.When(string.Format("In ENS04020 enter search string as \"{0}\" \"{1}\"", selection, searchString), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.Then(string.Format("In ENS04020 I should see Class Statistics Enquiry details as \"{0}\" \"{1}\" \"{2}\" \"{" +
                        "3}\" \"{4}\" \"{5}\" \"{6}\"", line1Pg2, line2Pg2, line3Pg2, line4Pg2, line5Pg2, line6Pg2, line7Pg2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 40
 testRunner.When(string.Format("In ENS04020 enter search string as \"{0}\" \"{1}\"", selection1, searchString1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 41
 testRunner.Then(string.Format("In ENS04020 I should see Class Statistics Enquiry details as \"{0}\" \"{1}\" \"{2}\" \"{" +
                        "3}\" \"{4}\" \"{5}\" \"{6}\"", line1Pg3, line2Pg3, line3Pg3, line4Pg3, line5Pg3, line6Pg3, line7Pg3), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18482: 03_IC Issued Capital Enquiry")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("DIV_A")]
        [NUnit.Framework.CategoryAttribute("EN_SE_StatisticsEnquiry")]
        [NUnit.Framework.CategoryAttribute("18482")]
        [NUnit.Framework.TestCaseAttribute("IC", "ACC", "DA1", "ESC", "FP", "", "", "", "", "", "", "LON", "MAL", "OR1", "OR2", "OR3", "", "", "", "Issuer", "Issuer", "Issuer", "Cert", "Issuer", "Chess", "FP  Totals", "Issuer", "Chess", "INT Totals", "Issuer", "Issuer", "Issuer", "Issuer", "Issuer", "Chess", "OR3 Totals", "Issuer", "40000", "20000", "203730", "400", "268750920", "914540698", "1183292018", "20000", "80", "20080", "300", "11", "100", "100", "100", "80", "180", "100", "40000", "20000", "203730", "400", "268751080", "914540698", "1183292178", "20000", "80", "20080", "300", "11", "100", "100", "100", "80", "180", "100", "40000", "20000", "203730", "400", "268751080", "914540698", "1183292178", "20000", "80", "20080", "300", "11", "100", "100", "100", "80", "180", "100", null)]
        public virtual void TestCase1848203_ICIssuedCapitalEnquiry(
                    string action, 
                    string class1, 
                    string class2, 
                    string class3, 
                    string class4, 
                    string class5, 
                    string class6, 
                    string class7, 
                    string class8, 
                    string class9, 
                    string class10, 
                    string class11, 
                    string class12, 
                    string class13, 
                    string class14, 
                    string class15, 
                    string class16, 
                    string class17, 
                    string class18, 
                    string classDesc1, 
                    string classDesc2, 
                    string classDesc3, 
                    string classDesc4, 
                    string classDesc5, 
                    string classDesc6, 
                    string classDesc7, 
                    string classDesc8, 
                    string classDesc9, 
                    string classDesc10, 
                    string classDesc11, 
                    string classDesc12, 
                    string classDesc13, 
                    string classDesc14, 
                    string classDesc15, 
                    string classDesc16, 
                    string classDesc17, 
                    string classDesc18, 
                    string eOM1, 
                    string eOM2, 
                    string eOM3, 
                    string eOM4, 
                    string eOM5, 
                    string eOM6, 
                    string eOM7, 
                    string eOM8, 
                    string eOM9, 
                    string eOM10, 
                    string eOM11, 
                    string eOM12, 
                    string eOM13, 
                    string eOM14, 
                    string eOM15, 
                    string eOM16, 
                    string eOM17, 
                    string eOM18, 
                    string lastRun1, 
                    string lastRun2, 
                    string lastRun3, 
                    string lastRun4, 
                    string lastRun5, 
                    string lastRun6, 
                    string lastRun7, 
                    string lastRun8, 
                    string lastRun9, 
                    string lastRun10, 
                    string lastRun11, 
                    string lastRun12, 
                    string lastRun13, 
                    string lastRun14, 
                    string lastRun15, 
                    string lastRun16, 
                    string lastRun17, 
                    string lastRun18, 
                    string current1, 
                    string current2, 
                    string current3, 
                    string current4, 
                    string current5, 
                    string current6, 
                    string current7, 
                    string current8, 
                    string current9, 
                    string current10, 
                    string current11, 
                    string current12, 
                    string current13, 
                    string current14, 
                    string current15, 
                    string current16, 
                    string current17, 
                    string current18, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "EnquiryTest",
                    "DIV_A",
                    "EN_SE_StatisticsEnquiry",
                    "18482"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18482: 03_IC Issued Capital Enquiry", @__tags);
#line 52
this.ScenarioSetup(scenarioInfo);
#line 54
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 55
 testRunner.When("In SELCOY01 I select the company: \"DIV_A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
  testRunner.And("I go to Statistics Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
  testRunner.And(string.Format("In ENS04010 I Select Statistic Enquiry action as \"{0}\"", action), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.Then(string.Format("In ENS04030 I should see Class codes as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\"" +
                        " \"{7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" \"{17}\"", class1, class2, class3, class4, class5, class6, class7, class8, class9, class10, class11, class12, class13, class14, class15, class16, class17, class18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 59
 testRunner.Then(string.Format("In ENS04030 I should see Class Description codes as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\"" +
                        " \"{5}\" \"{6}\" \"{7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" " +
                        "\"{17}\"", classDesc1, classDesc2, classDesc3, classDesc4, classDesc5, classDesc6, classDesc7, classDesc8, classDesc9, classDesc10, classDesc11, classDesc12, classDesc13, classDesc14, classDesc15, classDesc16, classDesc17, classDesc18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 60
 testRunner.Then(string.Format("In ENS04030 I should see EOM as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\" \"{7}\" \"" +
                        "{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" \"{17}\"", eOM1, eOM2, eOM3, eOM4, eOM5, eOM6, eOM7, eOM8, eOM9, eOM10, eOM11, eOM12, eOM13, eOM14, eOM15, eOM16, eOM17, eOM18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 61
 testRunner.Then(string.Format("In ENS04030 I should see Last Run as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\" \"{" +
                        "7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" \"{17}\"", lastRun1, lastRun2, lastRun3, lastRun4, lastRun5, lastRun6, lastRun7, lastRun8, lastRun9, lastRun10, lastRun11, lastRun12, lastRun13, lastRun14, lastRun15, lastRun16, lastRun17, lastRun18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 62
 testRunner.Then(string.Format("In ENS04030 I should see Current run as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\"" +
                        " \"{7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" \"{17}\"", current1, current2, current3, current4, current5, current6, current7, current8, current9, current10, current11, current12, current13, current14, current15, current16, current17, current18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18482: 03_IC Issued Capital Enquiry -Forward")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("DIV_A")]
        [NUnit.Framework.CategoryAttribute("EN_SE_StatisticsEnquiry")]
        [NUnit.Framework.CategoryAttribute("18482")]
        [NUnit.Framework.TestCaseAttribute("IC", "", "", "OR5", "", "", "OR6", "", "", "OR7", "", "", "ORD", "", "", "", "", "SPE", "", "Chess", "OR4 Totals", "Issuer", "Chess", "OR5 Totals", "Issuer", "Chess", "OR6 Totals", "Issuer", "Chess", "OR7 Totals", "Cert", "Issuer", "NZL-N", "Chess", "ORD Totals", "Issuer", "Chess", "80", "180", "100", "80", "180", "100", "80", "180", "200", "80", "280", "300", "45811707", "300", "11075116", "56887423", "33752523", "11304527", "80", "180", "100", "80", "180", "100", "80", "180", "200", "80", "280", "2300", "51292102", "300", "15049414", "66344116", "33752523", "11304527", "80", "180", "100", "80", "180", "100", "80", "180", "200", "80", "280", "2300", "51292102", "300", "15049414", "66344116", "33752523", "11304527", "F", "", null)]
        public virtual void TestCase1848203_ICIssuedCapitalEnquiry_Forward(
                    string action, 
                    string class1, 
                    string class2, 
                    string class3, 
                    string class4, 
                    string class5, 
                    string class6, 
                    string class7, 
                    string class8, 
                    string class9, 
                    string class10, 
                    string class11, 
                    string class12, 
                    string class13, 
                    string class14, 
                    string class15, 
                    string class16, 
                    string class17, 
                    string class18, 
                    string classDesc1, 
                    string classDesc2, 
                    string classDesc3, 
                    string classDesc4, 
                    string classDesc5, 
                    string classDesc6, 
                    string classDesc7, 
                    string classDesc8, 
                    string classDesc9, 
                    string classDesc10, 
                    string classDesc11, 
                    string classDesc12, 
                    string classDesc13, 
                    string classDesc14, 
                    string classDesc15, 
                    string classDesc16, 
                    string classDesc17, 
                    string classDesc18, 
                    string eOM1, 
                    string eOM2, 
                    string eOM3, 
                    string eOM4, 
                    string eOM5, 
                    string eOM6, 
                    string eOM7, 
                    string eOM8, 
                    string eOM9, 
                    string eOM10, 
                    string eOM11, 
                    string eOM12, 
                    string eOM13, 
                    string eOM14, 
                    string eOM15, 
                    string eOM16, 
                    string eOM17, 
                    string eOM18, 
                    string lastRun1, 
                    string lastRun2, 
                    string lastRun3, 
                    string lastRun4, 
                    string lastRun5, 
                    string lastRun6, 
                    string lastRun7, 
                    string lastRun8, 
                    string lastRun9, 
                    string lastRun10, 
                    string lastRun11, 
                    string lastRun12, 
                    string lastRun13, 
                    string lastRun14, 
                    string lastRun15, 
                    string lastRun16, 
                    string lastRun17, 
                    string lastRun18, 
                    string current1, 
                    string current2, 
                    string current3, 
                    string current4, 
                    string current5, 
                    string current6, 
                    string current7, 
                    string current8, 
                    string current9, 
                    string current10, 
                    string current11, 
                    string current12, 
                    string current13, 
                    string current14, 
                    string current15, 
                    string current16, 
                    string current17, 
                    string current18, 
                    string selection, 
                    string searchString, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "EnquiryTest",
                    "DIV_A",
                    "EN_SE_StatisticsEnquiry",
                    "18482"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18482: 03_IC Issued Capital Enquiry -Forward", @__tags);
#line 73
this.ScenarioSetup(scenarioInfo);
#line 75
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 76
 testRunner.When("In SELCOY01 I select the company: \"DIV_A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 77
  testRunner.And("I go to Statistics Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
  testRunner.And(string.Format("In ENS04010 I Select Statistic Enquiry action as \"{0}\"", action), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.When(string.Format("In ENS04030 enter search string as \"{0}\" \"{1}\"", selection, searchString), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 80
 testRunner.Then(string.Format("In ENS04030 I should see Class codes as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\"" +
                        " \"{7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" \"{17}\"", class1, class2, class3, class4, class5, class6, class7, class8, class9, class10, class11, class12, class13, class14, class15, class16, class17, class18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 81
 testRunner.Then(string.Format("In ENS04030 I should see Class Description codes as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\"" +
                        " \"{5}\" \"{6}\" \"{7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" " +
                        "\"{17}\"", classDesc1, classDesc2, classDesc3, classDesc4, classDesc5, classDesc6, classDesc7, classDesc8, classDesc9, classDesc10, classDesc11, classDesc12, classDesc13, classDesc14, classDesc15, classDesc16, classDesc17, classDesc18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 82
 testRunner.Then(string.Format("In ENS04030 I should see EOM as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\" \"{7}\" \"" +
                        "{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" \"{17}\"", eOM1, eOM2, eOM3, eOM4, eOM5, eOM6, eOM7, eOM8, eOM9, eOM10, eOM11, eOM12, eOM13, eOM14, eOM15, eOM16, eOM17, eOM18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 83
 testRunner.Then(string.Format("In ENS04030 I should see Last Run as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\" \"{" +
                        "7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" \"{17}\"", lastRun1, lastRun2, lastRun3, lastRun4, lastRun5, lastRun6, lastRun7, lastRun8, lastRun9, lastRun10, lastRun11, lastRun12, lastRun13, lastRun14, lastRun15, lastRun16, lastRun17, lastRun18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 84
 testRunner.Then(string.Format("In ENS04030 I should see Current run as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\"" +
                        " \"{7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" \"{17}\"", current1, current2, current3, current4, current5, current6, current7, current8, current9, current10, current11, current12, current13, current14, current15, current16, current17, current18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18482: 03_IC Issued Capital Enquiry -Search")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("DIV_A")]
        [NUnit.Framework.CategoryAttribute("EN_SE_StatisticsEnquiry")]
        [NUnit.Framework.CategoryAttribute("18482")]
        [NUnit.Framework.TestCaseAttribute("IC", "ORZ", "", "", "OWC", "", "", "OWD", "", "", "SUE", "", "", "", "", "", "", "", "", "Issuer", "Chess", "ORZ Totals", "Issuer", "Chess", "OWC Totals", "Issuer", "Chess", "OWD Totals", "Cert", "Issuer", "SUE Totals", "", "", "", "", "", "", "4927", "", "4927", "32856908", "10980556", "43837464", "32807101", "11036283", "43843384", "40", "510", "550", "", "", "", "", "", "", "4927", "1000", "5927", "32856908", "10980556", "43837464", "32807101", "11036283", "43843384", "40", "510", "550", "", "", "", "", "", "", "4927", "1000", "5927", "32856908", "10980556", "43837464", "32807101", "11036283", "43843384", "40", "510", "550", "", "", "", "", "", "", "S", "ORZ", null)]
        public virtual void TestCase1848203_ICIssuedCapitalEnquiry_Search(
                    string action, 
                    string class1, 
                    string class2, 
                    string class3, 
                    string class4, 
                    string class5, 
                    string class6, 
                    string class7, 
                    string class8, 
                    string class9, 
                    string class10, 
                    string class11, 
                    string class12, 
                    string class13, 
                    string class14, 
                    string class15, 
                    string class16, 
                    string class17, 
                    string class18, 
                    string classDesc1, 
                    string classDesc2, 
                    string classDesc3, 
                    string classDesc4, 
                    string classDesc5, 
                    string classDesc6, 
                    string classDesc7, 
                    string classDesc8, 
                    string classDesc9, 
                    string classDesc10, 
                    string classDesc11, 
                    string classDesc12, 
                    string classDesc13, 
                    string classDesc14, 
                    string classDesc15, 
                    string classDesc16, 
                    string classDesc17, 
                    string classDesc18, 
                    string eOM1, 
                    string eOM2, 
                    string eOM3, 
                    string eOM4, 
                    string eOM5, 
                    string eOM6, 
                    string eOM7, 
                    string eOM8, 
                    string eOM9, 
                    string eOM10, 
                    string eOM11, 
                    string eOM12, 
                    string eOM13, 
                    string eOM14, 
                    string eOM15, 
                    string eOM16, 
                    string eOM17, 
                    string eOM18, 
                    string lastRun1, 
                    string lastRun2, 
                    string lastRun3, 
                    string lastRun4, 
                    string lastRun5, 
                    string lastRun6, 
                    string lastRun7, 
                    string lastRun8, 
                    string lastRun9, 
                    string lastRun10, 
                    string lastRun11, 
                    string lastRun12, 
                    string lastRun13, 
                    string lastRun14, 
                    string lastRun15, 
                    string lastRun16, 
                    string lastRun17, 
                    string lastRun18, 
                    string current1, 
                    string current2, 
                    string current3, 
                    string current4, 
                    string current5, 
                    string current6, 
                    string current7, 
                    string current8, 
                    string current9, 
                    string current10, 
                    string current11, 
                    string current12, 
                    string current13, 
                    string current14, 
                    string current15, 
                    string current16, 
                    string current17, 
                    string current18, 
                    string selection, 
                    string searchString, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "EnquiryTest",
                    "DIV_A",
                    "EN_SE_StatisticsEnquiry",
                    "18482"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18482: 03_IC Issued Capital Enquiry -Search", @__tags);
#line 95
this.ScenarioSetup(scenarioInfo);
#line 97
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 98
 testRunner.When("In SELCOY01 I select the company: \"DIV_A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 99
  testRunner.And("I go to Statistics Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
  testRunner.And(string.Format("In ENS04010 I Select Statistic Enquiry action as \"{0}\"", action), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 101
 testRunner.When(string.Format("In ENS04030 enter search string as \"{0}\" \"{1}\"", selection, searchString), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 102
 testRunner.Then(string.Format("In ENS04030 I should see Class codes as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\"" +
                        " \"{7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" \"{17}\"", class1, class2, class3, class4, class5, class6, class7, class8, class9, class10, class11, class12, class13, class14, class15, class16, class17, class18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 103
 testRunner.Then(string.Format("In ENS04030 I should see Class Description codes as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\"" +
                        " \"{5}\" \"{6}\" \"{7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" " +
                        "\"{17}\"", classDesc1, classDesc2, classDesc3, classDesc4, classDesc5, classDesc6, classDesc7, classDesc8, classDesc9, classDesc10, classDesc11, classDesc12, classDesc13, classDesc14, classDesc15, classDesc16, classDesc17, classDesc18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 104
 testRunner.Then(string.Format("In ENS04030 I should see EOM as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\" \"{7}\" \"" +
                        "{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" \"{17}\"", eOM1, eOM2, eOM3, eOM4, eOM5, eOM6, eOM7, eOM8, eOM9, eOM10, eOM11, eOM12, eOM13, eOM14, eOM15, eOM16, eOM17, eOM18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 105
 testRunner.Then(string.Format("In ENS04030 I should see Last Run as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\" \"{" +
                        "7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" \"{17}\"", lastRun1, lastRun2, lastRun3, lastRun4, lastRun5, lastRun6, lastRun7, lastRun8, lastRun9, lastRun10, lastRun11, lastRun12, lastRun13, lastRun14, lastRun15, lastRun16, lastRun17, lastRun18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 106
 testRunner.Then(string.Format("In ENS04030 I should see Current run as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{6}\"" +
                        " \"{7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\" \"{15}\" \"{16}\" \"{17}\"", current1, current2, current3, current4, current5, current6, current7, current8, current9, current10, current11, current12, current13, current14, current15, current16, current17, current18), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 18659: 05_ Options")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("EnquiryTest")]
        [NUnit.Framework.CategoryAttribute("DIV_A")]
        [NUnit.Framework.CategoryAttribute("EN_SE_StatisticsEnquiry")]
        [NUnit.Framework.CategoryAttribute("18659")]
        [NUnit.Framework.TestCaseAttribute("T200", "ESC", "GWOG        HOLDINGSPTYLTD", "", "** TOTALS FOR CLASS ESC**", "I0030001061", "", "", "203730", "", "203730", "100.00", "", "100.00", "1", "", "", "", "ADAK        RZBOWJ", "ADFOHUKLO   CDEUH", "", "I0030190157", "I0030135300", "", "10000", "10000", "", "50.00", "50.00", "", "1", "2", "", null)]
        [NUnit.Framework.TestCaseAttribute("G200", "ESC", "GWOG        HOLDINGSPTYLTD", "", "** TOTALS FOR CLASS ESC**", "I0030001061", "", "", "203730", "", "203730", "100.00", "", "100.00", "1", "", "", "", "ADAK        RZBOWJ", "ADFOHUKLO   CDEUH", "", "I0030190157", "I0030135300", "", "10000", "10000", "", "50.00", "50.00", "", "1", "2", "", null)]
        public virtual void TestCase1865905_Options(
                    string action, 
                    string @class, 
                    string name1, 
                    string name2, 
                    string name3, 
                    string hIN1, 
                    string hIN2, 
                    string hIN3, 
                    string units1, 
                    string units2, 
                    string units3, 
                    string iC1, 
                    string iC2, 
                    string iC3, 
                    string rank1, 
                    string rank2, 
                    string rank3, 
                    string class1, 
                    string name1Pg1, 
                    string name2Pg1, 
                    string name3Pg1, 
                    string hIN1Pg1, 
                    string hIN2Pg1, 
                    string hIN3Pg1, 
                    string units1Pg1, 
                    string units2Pg1, 
                    string units3Pg1, 
                    string iC1Pg1, 
                    string iC2Pg1, 
                    string iC3Pg1, 
                    string rank1Pg1, 
                    string rank2Pg1, 
                    string rank3Pg1, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "EnquiryTest",
                    "DIV_A",
                    "EN_SE_StatisticsEnquiry",
                    "18659"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 18659: 05_ Options", @__tags);
#line 139
this.ScenarioSetup(scenarioInfo);
#line 141
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 142
 testRunner.When("In SELCOY01 I select the company: \"DIV_A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 143
  testRunner.And("I go to Statistics Enquiry System", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 144
  testRunner.And(string.Format("In ENS04010 I Select Statistic Enquiry action as \"{0}\"", action), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 145
 testRunner.When(string.Format("In ENS04060 enter Class Code as \"{0}\"", @class), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 146
 testRunner.Then(string.Format("In ENS04070 I should see Top200 Balance as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{" +
                        "6}\" \"{7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\"", name1, name2, name3, hIN1, hIN2, hIN3, units1, units2, units3, iC1, iC2, iC3, rank1, rank2, rank3), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 147
 testRunner.When("I PressESC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 148
 testRunner.Then("I expect to be in the \"ENS04060\" Screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 149
 testRunner.When(string.Format("In ENS04060 enter Class Code as \"{0}\"", class1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 150
 testRunner.Then(string.Format("In ENS04070 I should see Top200 Balance as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{" +
                        "6}\" \"{7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\"", name1Pg1, name2Pg1, name3Pg1, hIN1Pg1, hIN2Pg1, hIN3Pg1, units1Pg1, units2Pg1, units3Pg1, iC1Pg1, iC2Pg1, iC3Pg1, rank1Pg1, rank2Pg1, rank3Pg1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 151
 testRunner.When("I Transmit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 152
 testRunner.Then(string.Format("In ENS04070 I should see Top200 Balance as \"{0}\" \"{1}\" \"{2}\" \"{3}\" \"{4}\" \"{5}\" \"{" +
                        "6}\" \"{7}\" \"{8}\" \"{9}\" \"{10}\" \"{11}\" \"{12}\" \"{13}\" \"{14}\"", name1, name2, name3, hIN1, hIN2, hIN3, units1, units2, units3, iC1, iC2, iC3, rank1, rank2, rank3), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
