// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SCRIPAU.Automation.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("OL_DPM_DividendPlanMaintenance")]
    [NUnit.Framework.CategoryAttribute("setup_feature")]
    public partial class OL_DPM_DividendPlanMaintenanceFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "OL_DPM_DividendPlanMaintenance.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "OL_DPM_DividendPlanMaintenance", "Ensure DPM. Dividend Plan Maintenance functionality covered", ProgrammingLanguage.CSharp, new string[] {
                        "setup_feature"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Dividend Intention -Partial")]
        [NUnit.Framework.CategoryAttribute("CPU_AUTO")]
        [NUnit.Framework.CategoryAttribute("OL_DPM_DividendPlanMaintenance")]
        [NUnit.Framework.CategoryAttribute("OL_Online")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        public virtual void AddDividendIntention_Partial()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Dividend Intention -Partial", new string[] {
                        "CPU_AUTO",
                        "OL_DPM_DividendPlanMaintenance",
                        "OL_Online",
                        "winformsTest"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 11
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
 testRunner.When("In SELCOY01 I select the company: \"CPU_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
  testRunner.And("I Go to Dividend Plan Maintenance Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
  testRunner.And("I select \"DIVIT\" Transaction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "HIN",
                        "I0100007762"});
            table1.AddRow(new string[] {
                        "Tran No",
                        "156"});
            table1.AddRow(new string[] {
                        "Tran Date",
                        "13/04/15"});
            table1.AddRow(new string[] {
                        "DRP Option",
                        "P"});
            table1.AddRow(new string[] {
                        "DRP Level",
                        "100"});
#line 15
 testRunner.When("I update the \"partial\" Dividend Intention as below:", ((string)(null)), table1, "When ");
#line 22
  testRunner.And("I go to the Enquiry system for \"I0100007762\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "Action",
                        "DI"});
            table2.AddRow(new string[] {
                        "Locate Argument",
                        ""});
#line 23
  testRunner.And("I enter the following details as the Locate action:", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "HIN",
                        "I0100007762"});
            table3.AddRow(new string[] {
                        "DRP Intention",
                        "DRP5  5   FP DRP       13/04/15            4402       156    P        100  N"});
#line 27
  testRunner.Then("In ENS01060 I should see holder Dividend Intention Details as below:", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Dividend Intention -Full")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("OL_Online")]
        [NUnit.Framework.CategoryAttribute("CPU_AUTO")]
        [NUnit.Framework.CategoryAttribute("OL_DPM_DividendPlanMaintenance")]
        public virtual void AddDividendIntention_Full()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Dividend Intention -Full", new string[] {
                        "winformsTest",
                        "OL_Online",
                        "CPU_AUTO",
                        "OL_DPM_DividendPlanMaintenance"});
#line 36
this.ScenarioSetup(scenarioInfo);
#line 37
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 38
 testRunner.When("In SELCOY01 I select the company: \"CPU_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
  testRunner.And("I Go to Dividend Plan Maintenance Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
  testRunner.And("I select \"DIVIT\" Transaction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "HIN",
                        "I0100007754"});
            table4.AddRow(new string[] {
                        "Tran No",
                        "157"});
            table4.AddRow(new string[] {
                        "Tran Date",
                        "13/04/15"});
            table4.AddRow(new string[] {
                        "DRP Option",
                        "F"});
#line 41
 testRunner.When("I update the \"full\" Dividend Intention as below:", ((string)(null)), table4, "When ");
#line 47
  testRunner.And("I go to the Enquiry system for \"I0100007754\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "Action",
                        "DI"});
            table5.AddRow(new string[] {
                        "Locate Argument",
                        ""});
#line 48
  testRunner.And("I enter the following details as the Locate action:", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table6.AddRow(new string[] {
                        "HIN",
                        "I0100007754"});
            table6.AddRow(new string[] {
                        "DRP Intention",
                        "DRP5  5   FP DRP       13/04/15            4402       157    F             N"});
#line 52
  testRunner.Then("In ENS01060 I should see holder Dividend Intention Details as below:", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DividendplanIntention_Transactions")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("OL_Online")]
        [NUnit.Framework.CategoryAttribute("ANZ_AUTO")]
        [NUnit.Framework.CategoryAttribute("21093")]
        [NUnit.Framework.CategoryAttribute("21094")]
        [NUnit.Framework.CategoryAttribute("OL_DPM_DividendPlanMaintenance")]
        [NUnit.Framework.TestCaseAttribute("Test2", "DIVIT", "s", "X0049846177", "U", "", "42421", "", "F", "", "", "", "", "", "", "", "", "", "N", "", "", "", "", "20", "", "", "", "", "C", "", "DI", "", "BOP1  1   BOP                                                              Y", "", "", "", "BOP5  5   BONUS PLAN   NON PARTICIPANT", "42421    N         20  N", "DPN2  2   DRP PLAN     NON PARTICIPANT", "DPN3  3   DRP PLAN     NON PARTICIPANT", "DPN4  4   DRP PLAN     NON PARTICIPANT", "DPN5  5   DRP PLAN     NON PARTICIPANT", null)]
        [NUnit.Framework.TestCaseAttribute("Test3", "DIVIT", "s", "X0027783953", "U", "", "42422", "", "F", "", "", "", "", "", "", "", "", "", "P", "", "", "", "", "50", "", "", "", "", "C", "", "DI", "", "BOP1  1   BOP                                                              Y", "", "", "", "BOP5  5   BONUS PLAN   NON PARTICIPANT", "42422    P         50  N", "DPN2  2   DRP PLAN     NON PARTICIPANT", "DPN3  3   DRP PLAN     NON PARTICIPANT", "DPN4  4   DRP PLAN     NON PARTICIPANT", "DPN5  5   DRP PLAN     NON PARTICIPANT", null)]
        public virtual void DividendplanIntention_Transactions(
                    string test, 
                    string selCode, 
                    string action, 
                    string searchData, 
                    string action1, 
                    string searchData1, 
                    string transNumber, 
                    string date, 
                    string bspOpt1, 
                    string bspOpt2, 
                    string bspOpt3, 
                    string bspOpt4, 
                    string bspOpt5, 
                    string bspLev1, 
                    string bspLev2, 
                    string bspLev3, 
                    string bspLev4, 
                    string bspLev5, 
                    string drpOpt1, 
                    string drpOpt2, 
                    string drpOpt3, 
                    string drpOpt4, 
                    string drpOpt5, 
                    string drpLev1, 
                    string drpLev2, 
                    string drpLev3, 
                    string drpLev4, 
                    string drpLev5, 
                    string sourceOption, 
                    string confirm, 
                    string action2, 
                    string locateArgument, 
                    string bspLine1, 
                    string bspLine2, 
                    string bspLine3, 
                    string bspLine4, 
                    string bspLine5, 
                    string drpLine1, 
                    string drpLine2, 
                    string drpLine3, 
                    string drpLine4, 
                    string drpLine5, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "OL_Online",
                    "ANZ_AUTO",
                    "21093",
                    "21094",
                    "OL_DPM_DividendPlanMaintenance"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DividendplanIntention_Transactions", @__tags);
#line 63
this.ScenarioSetup(scenarioInfo);
#line 66
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 67
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
  testRunner.And("In MNS00101 I click on: \"online data entry system\" within the System Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
  testRunner.And("In OLS00101 I Click on: \"dividend plan maintenance\" with in the online data entry" +
                    " system menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "SelCode"});
            table7.AddRow(new string[] {
                        string.Format("{0}", selCode)});
#line 70
  testRunner.And("In SELTRN20 I continue with the following details:", ((string)(null)), table7, "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Action",
                        "SearchData"});
            table8.AddRow(new string[] {
                        string.Format("{0}", action),
                        string.Format("{0}", searchData)});
#line 73
  testRunner.And("In OLS01511 I continue with the following details:", ((string)(null)), table8, "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Action",
                        "SearchData"});
            table9.AddRow(new string[] {
                        string.Format("{0}", action1),
                        string.Format("{0}", searchData1)});
#line 76
  testRunner.And("In OLS01511 I continue with the following details:", ((string)(null)), table9, "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "TransNumber",
                        "Date",
                        "BspOpt1",
                        "BspOpt2",
                        "BspOpt3",
                        "BspOpt4",
                        "BspOpt5",
                        "BspLev1",
                        "BspLev2",
                        "BspLev3",
                        "BspLev4",
                        "BspLev5",
                        "DrpOpt1",
                        "DrpOpt2",
                        "DrpOpt3",
                        "DrpOpt4",
                        "DrpOpt5",
                        "DrpLev1",
                        "DrpLev2",
                        "DrpLev3",
                        "DrpLev4",
                        "DrpLev5",
                        "SourceOption"});
            table10.AddRow(new string[] {
                        string.Format("{0}", transNumber),
                        string.Format("{0}", date),
                        string.Format("{0}", bspOpt1),
                        string.Format("{0}", bspOpt2),
                        string.Format("{0}", bspOpt3),
                        string.Format("{0}", bspOpt4),
                        string.Format("{0}", bspOpt5),
                        string.Format("{0}", bspLev1),
                        string.Format("{0}", bspLev2),
                        string.Format("{0}", bspLev3),
                        string.Format("{0}", bspLev4),
                        string.Format("{0}", bspLev5),
                        string.Format("{0}", drpOpt1),
                        string.Format("{0}", drpOpt2),
                        string.Format("{0}", drpOpt3),
                        string.Format("{0}", drpOpt4),
                        string.Format("{0}", drpOpt5),
                        string.Format("{0}", drpLev1),
                        string.Format("{0}", drpLev2),
                        string.Format("{0}", drpLev3),
                        string.Format("{0}", drpLev4),
                        string.Format("{0}", drpLev5),
                        string.Format("{0}", sourceOption)});
#line 79
  testRunner.And("In OLS01501 I continue with the following details:", ((string)(null)), table10, "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Confirm"});
            table11.AddRow(new string[] {
                        string.Format("{0}", confirm)});
#line 82
  testRunner.And("In OLS01502 I continue with the following details:", ((string)(null)), table11, "And ");
#line 85
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 86
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 87
  testRunner.And(string.Format("I go to the Enquiry system and Search {0}", searchData), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
  testRunner.And(string.Format("I enter the following details as the Locate action \"{0}\" \"{1}\"", action2, locateArgument), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "BspLine1",
                        "BspLine2",
                        "BspLine3",
                        "BspLine4",
                        "BspLine5",
                        "SourceOption",
                        "DrpLine1",
                        "DrpLine2",
                        "DrpLine3",
                        "DrpLine4",
                        "DrpLine5"});
            table12.AddRow(new string[] {
                        string.Format("{0}", bspLine1),
                        string.Format("{0}", bspLine2),
                        string.Format("{0}", bspLine3),
                        string.Format("{0}", bspLine4),
                        string.Format("{0}", bspLine5),
                        string.Format("{0}", sourceOption),
                        string.Format("{0}", drpLine1),
                        string.Format("{0}", drpLine2),
                        string.Format("{0}", drpLine3),
                        string.Format("{0}", drpLine4),
                        string.Format("{0}", drpLine5)});
#line 89
 testRunner.Then("In ENS01060 I verify the following details:", ((string)(null)), table12, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Testcase21097_DPI_ErrorValidation")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("OL_Online")]
        [NUnit.Framework.CategoryAttribute("ANZ_AUTO")]
        [NUnit.Framework.CategoryAttribute("21097")]
        [NUnit.Framework.CategoryAttribute("OL_DPM_DividendPlanMaintenance")]
        [NUnit.Framework.TestCaseAttribute("Test1", "DIVIT", "s", "X0023842165", "U", "", "42423", "", "K", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "D", "Participation Option not valid for this plan", null)]
        [NUnit.Framework.TestCaseAttribute("Test2", "DIVIT", "s", "X0023842165", "U", "", "42423", "", "P", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "D", "A level MUST be entered for <P>artial participants", null)]
        [NUnit.Framework.TestCaseAttribute("Test3", "DIVIT", "s", "X0023842165", "U", "", "42423", "", "W", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "D", "Invalid action - CANNOT withdraw this holder as", null)]
        [NUnit.Framework.TestCaseAttribute("Test4", "DIVIT", "s", "X0023842165", "U", "", "42423", "", "F", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "B", "Invalid action - to remove a holder from a plan", null)]
        public virtual void Testcase21097_DPI_ErrorValidation(
                    string test, 
                    string selCode, 
                    string action, 
                    string searchData, 
                    string action1, 
                    string searchData1, 
                    string transNumber, 
                    string date, 
                    string bspOpt1, 
                    string bspOpt2, 
                    string bspOpt3, 
                    string bspOpt4, 
                    string bspOpt5, 
                    string bspLev1, 
                    string bspLev2, 
                    string bspLev3, 
                    string bspLev4, 
                    string bspLev5, 
                    string drpOpt1, 
                    string drpOpt2, 
                    string drpOpt3, 
                    string drpOpt4, 
                    string drpOpt5, 
                    string drpLev1, 
                    string drpLev2, 
                    string drpLev3, 
                    string drpLev4, 
                    string drpLev5, 
                    string sourceOption, 
                    string errorMessage, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "OL_Online",
                    "ANZ_AUTO",
                    "21097",
                    "OL_DPM_DividendPlanMaintenance"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Testcase21097_DPI_ErrorValidation", @__tags);
#line 104
this.ScenarioSetup(scenarioInfo);
#line 106
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 107
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 108
  testRunner.And("In MNS00101 I click on: \"online data entry system\" within the System Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 109
  testRunner.And("In OLS00101 I Click on: \"dividend plan maintenance\" with in the online data entry" +
                    " system menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "SelCode"});
            table13.AddRow(new string[] {
                        string.Format("{0}", selCode)});
#line 110
  testRunner.And("In SELTRN20 I continue with the following details:", ((string)(null)), table13, "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Action",
                        "SearchData"});
            table14.AddRow(new string[] {
                        string.Format("{0}", action),
                        string.Format("{0}", searchData)});
#line 113
  testRunner.And("In OLS01511 I continue with the following details:", ((string)(null)), table14, "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Action",
                        "SearchData"});
            table15.AddRow(new string[] {
                        string.Format("{0}", action1),
                        string.Format("{0}", searchData1)});
#line 116
  testRunner.And("In OLS01511 I continue with the following details:", ((string)(null)), table15, "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "TransNumber",
                        "Date",
                        "BspOpt1",
                        "BspOpt2",
                        "BspOpt3",
                        "BspOpt4",
                        "BspOpt5",
                        "BspLev1",
                        "BspLev2",
                        "BspLev3",
                        "BspLev4",
                        "BspLev5",
                        "DrpOpt1",
                        "DrpOpt2",
                        "DrpOpt3",
                        "DrpOpt4",
                        "DrpOpt5",
                        "DrpLev1",
                        "DrpLev2",
                        "DrpLev3",
                        "DrpLev4",
                        "DrpLev5",
                        "SourceOption"});
            table16.AddRow(new string[] {
                        string.Format("{0}", transNumber),
                        string.Format("{0}", date),
                        string.Format("{0}", bspOpt1),
                        string.Format("{0}", bspOpt2),
                        string.Format("{0}", bspOpt3),
                        string.Format("{0}", bspOpt4),
                        string.Format("{0}", bspOpt5),
                        string.Format("{0}", bspLev1),
                        string.Format("{0}", bspLev2),
                        string.Format("{0}", bspLev3),
                        string.Format("{0}", bspLev4),
                        string.Format("{0}", bspLev5),
                        string.Format("{0}", drpOpt1),
                        string.Format("{0}", drpOpt2),
                        string.Format("{0}", drpOpt3),
                        string.Format("{0}", drpOpt4),
                        string.Format("{0}", drpOpt5),
                        string.Format("{0}", drpLev1),
                        string.Format("{0}", drpLev2),
                        string.Format("{0}", drpLev3),
                        string.Format("{0}", drpLev4),
                        string.Format("{0}", drpLev5),
                        string.Format("{0}", sourceOption)});
#line 119
  testRunner.And("In OLS01501 I continue with the following details:", ((string)(null)), table16, "And ");
#line 122
 testRunner.Then(string.Format("I should see the below ErrorMessage \"{0}\"", errorMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Testcase21334_MNYIN_Transaction")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("OL_Online")]
        [NUnit.Framework.CategoryAttribute("ANZ_AUTO")]
        [NUnit.Framework.CategoryAttribute("21334")]
        [NUnit.Framework.CategoryAttribute("OL_DPM_DividendPlanMaintenance")]
        [NUnit.Framework.TestCaseAttribute("Test1", "MNYIN", "42423", "", "500", "DRP1", "X0041248408", "DRP", "Z", "DRP RESIDUAL (ORD)", "", "C", "/Z", "Z  /DRP RESIDUAL (ORD)", "500.00", "**** Total for MONEY L/OVER           500.00", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("Test2", "MNYIN", "42424", "", "1500.30", "DRP1", "I0012680295", "DRP", "Z", "DRP RESIDUAL (ORD)", "20/07/2015", "C", "/Z", "Z  /DRP RESIDUAL (ORD)", "*MR MONEY L/OVER 18/12/08         10.20    *MR MONEY L/OVER 01/07/09           3." +
            "20", "*MR MONEY L/OVER 18/12/09         11.77-   *MR MONEY L/OVER 01/07/10           0." +
            "52", "*MR MONEY L/OVER 17/12/10         12.46    *MR MONEY L/OVER 01/07/11          10." +
            "36-", "*MR MONEY L/OVER 16/12/11          7.11    *MR MONEY L/OVER 02/07/12           0." +
            "78-", "*MR MONEY L/OVER 19/12/12         10.07-   *MR MONEY L/OVER 01/07/13          26." +
            "42", "*MR MONEY L/OVER 16/12/13          1.20-   *MR MONEY L/OVER 01/07/14          20." +
            "96-", "*MR MONEY L/OVER 16/12/14         14.44    *MR MONEY L/OVER 20/07/15        1500." +
            "30", "**** Total for MONEY L/OVER          1519.51", "", null)]
        public virtual void Testcase21334_MNYIN_Transaction(
                    string test, 
                    string selCode, 
                    string transNumber, 
                    string lodgeDate, 
                    string totalUnits, 
                    string buyPlan, 
                    string buyer, 
                    string buyPlanDesc, 
                    string buyClass, 
                    string buyClassDesc, 
                    string buyDate, 
                    string action, 
                    string locateArgument, 
                    string certificateLine1, 
                    string certificateLine2, 
                    string certificateLine3, 
                    string certificateLine4, 
                    string certificateLine5, 
                    string certificateLine6, 
                    string certificateLine7, 
                    string certificateLine8, 
                    string certificateLine9, 
                    string certificateLine10, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "OL_Online",
                    "ANZ_AUTO",
                    "21334",
                    "OL_DPM_DividendPlanMaintenance"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Testcase21334_MNYIN_Transaction", @__tags);
#line 137
this.ScenarioSetup(scenarioInfo);
#line 139
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 140
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 141
  testRunner.And("In MNS00101 I click on: \"online data entry system\" within the System Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
  testRunner.And("In OLS00101 I Click on: \"dividend plan maintenance\" with in the online data entry" +
                    " system menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "SelCode"});
            table17.AddRow(new string[] {
                        string.Format("{0}", selCode)});
#line 143
  testRunner.And("In SELTRN20 I continue with the following details:", ((string)(null)), table17, "And ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "TransNumber",
                        "LodgeDate",
                        "TotalUnits",
                        "BuyPlan",
                        "Buyer"});
            table18.AddRow(new string[] {
                        string.Format("{0}", transNumber),
                        string.Format("{0}", lodgeDate),
                        string.Format("{0}", totalUnits),
                        string.Format("{0}", buyPlan),
                        string.Format("{0}", buyer)});
#line 146
  testRunner.And("In OLS05001 I continue with the following details:", ((string)(null)), table18, "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "BuyPlan",
                        "BuyPlanDesc",
                        "BuyClass",
                        "BuyClassDesc",
                        "Buyer",
                        "BuyDate"});
            table19.AddRow(new string[] {
                        string.Format("{0}", buyPlan),
                        string.Format("{0}", buyPlanDesc),
                        string.Format("{0}", buyClass),
                        string.Format("{0}", buyClassDesc),
                        string.Format("{0}", buyer),
                        string.Format("{0}", buyDate)});
#line 149
  testRunner.And("In OLS05002 I continue with the following details:", ((string)(null)), table19, "And ");
#line 152
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 153
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 154
  testRunner.And(string.Format("I go to the Enquiry system and Search {0}", buyer), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 155
  testRunner.And(string.Format("I enter the following details as the Locate action \"{0}\" \"{1}\"", action, locateArgument), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "CertificateLine1",
                        "CertificateLine2",
                        "CertificateLine3",
                        "CertificateLine4",
                        "CertificateLine5",
                        "CertificateLine6",
                        "CertificateLine7",
                        "CertificateLine8",
                        "CertificateLine9",
                        "CertificateLine10"});
            table20.AddRow(new string[] {
                        string.Format("{0}", certificateLine1),
                        string.Format("{0}", certificateLine2),
                        string.Format("{0}", certificateLine3),
                        string.Format("{0}", certificateLine4),
                        string.Format("{0}", certificateLine5),
                        string.Format("{0}", certificateLine6),
                        string.Format("{0}", certificateLine7),
                        string.Format("{0}", certificateLine8),
                        string.Format("{0}", certificateLine9),
                        string.Format("{0}", certificateLine10)});
#line 156
 testRunner.Then("In ENS01012 I should see Register details as:", ((string)(null)), table20, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Testcase21335_MNYDN_Transaction")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("OL_Online")]
        [NUnit.Framework.CategoryAttribute("ANZ_AUTO")]
        [NUnit.Framework.CategoryAttribute("21335")]
        [NUnit.Framework.CategoryAttribute("OL_DPM_DividendPlanMaintenance")]
        [NUnit.Framework.TestCaseAttribute("Test1", "MNYDN", "42426", "", "100.00", "DRP1", "I0060200335", "DRP", "Z", "DRP RESIDUAL (ORD)", "", "H", "/Z", "*Z  /DRP RESIDUAL (ORD)      *MR        200.00                    200.00", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("Test2", "MNYDN", "42427", "", "320.50", "DRP1", "X0042573612", "DRP", "Z", "DRP RESIDUAL (ORD)", "", "H", "/Z", "*Z  /DRP RESIDUAL (ORD)      *MR        886.32                    886.32", "", "", "", "", null)]
        public virtual void Testcase21335_MNYDN_Transaction(
                    string test, 
                    string selCode, 
                    string transNumber, 
                    string lodgeDate, 
                    string totalUnits, 
                    string sellPlan, 
                    string seller, 
                    string sellPlanDesc, 
                    string sellClass, 
                    string sellClassDesc, 
                    string sellDate, 
                    string action, 
                    string locateArgument, 
                    string last6Lines1, 
                    string last6Lines2, 
                    string last6Lines3, 
                    string last6Lines4, 
                    string last6Lines5, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "OL_Online",
                    "ANZ_AUTO",
                    "21335",
                    "OL_DPM_DividendPlanMaintenance"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Testcase21335_MNYDN_Transaction", @__tags);
#line 171
this.ScenarioSetup(scenarioInfo);
#line 173
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 174
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 175
  testRunner.And("In MNS00101 I click on: \"online data entry system\" within the System Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 176
  testRunner.And("In OLS00101 I Click on: \"dividend plan maintenance\" with in the online data entry" +
                    " system menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "SelCode"});
            table21.AddRow(new string[] {
                        string.Format("{0}", selCode)});
#line 177
  testRunner.And("In SELTRN20 I continue with the following details:", ((string)(null)), table21, "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "TransNumber",
                        "LodgeDate",
                        "TotalUnits",
                        "SellPlan",
                        "Seller"});
            table22.AddRow(new string[] {
                        string.Format("{0}", transNumber),
                        string.Format("{0}", lodgeDate),
                        string.Format("{0}", totalUnits),
                        string.Format("{0}", sellPlan),
                        string.Format("{0}", seller)});
#line 180
  testRunner.And("In OLS05101 I continue with the following details:", ((string)(null)), table22, "And ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "SellPlan",
                        "SellPlanDesc",
                        "SellClass",
                        "SellClassDesc",
                        "Seller",
                        "SellDate"});
            table23.AddRow(new string[] {
                        string.Format("{0}", sellPlan),
                        string.Format("{0}", sellPlanDesc),
                        string.Format("{0}", sellClass),
                        string.Format("{0}", sellClassDesc),
                        string.Format("{0}", seller),
                        string.Format("{0}", sellDate)});
#line 183
  testRunner.And("In OLS05102 I continue with the following details:", ((string)(null)), table23, "And ");
#line 186
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 187
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 188
  testRunner.And(string.Format("I go to the Enquiry system and Search {0}", seller), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
  testRunner.And(string.Format("I enter the following details as the Locate action \"{0}\" \"{1}\"", action, locateArgument), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last6Lines1",
                        "Last6Lines2",
                        "Last6Lines3",
                        "Last6Lines4",
                        "Last6Lines5"});
            table24.AddRow(new string[] {
                        string.Format("{0}", last6Lines1),
                        string.Format("{0}", last6Lines2),
                        string.Format("{0}", last6Lines3),
                        string.Format("{0}", last6Lines4),
                        string.Format("{0}", last6Lines5)});
#line 190
 testRunner.Then("In ENS01007 I should see Holding details as:", ((string)(null)), table24, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Testcase21470_MNYIN_ErrorValidation")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("OL_Online")]
        [NUnit.Framework.CategoryAttribute("ANZ_AUTO")]
        [NUnit.Framework.CategoryAttribute("21470")]
        [NUnit.Framework.CategoryAttribute("OL_DPM_DividendPlanMaintenance")]
        [NUnit.Framework.TestCaseAttribute("Test1", "MNYIN", "42428", "", "80.50", "BOS1", "", "This plan is NOT a valid one for this company.", null)]
        [NUnit.Framework.TestCaseAttribute("Test2", "MNYIN", "42428", "", "80.50", "DRP1", "L0330468009", "Holder not an active participate in this plan", null)]
        public virtual void Testcase21470_MNYIN_ErrorValidation(string test, string selCode, string transNumber, string lodgeDate, string totalUnits, string buyPlan, string buyer, string errorMessage, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "OL_Online",
                    "ANZ_AUTO",
                    "21470",
                    "OL_DPM_DividendPlanMaintenance"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Testcase21470_MNYIN_ErrorValidation", @__tags);
#line 204
this.ScenarioSetup(scenarioInfo);
#line 206
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 207
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 208
  testRunner.And("In MNS00101 I click on: \"online data entry system\" within the System Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 209
  testRunner.And("In OLS00101 I Click on: \"dividend plan maintenance\" with in the online data entry" +
                    " system menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "SelCode"});
            table25.AddRow(new string[] {
                        string.Format("{0}", selCode)});
#line 210
  testRunner.And("In SELTRN20 I continue with the following details:", ((string)(null)), table25, "And ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "TransNumber",
                        "LodgeDate",
                        "TotalUnits",
                        "BuyPlan",
                        "Buyer"});
            table26.AddRow(new string[] {
                        string.Format("{0}", transNumber),
                        string.Format("{0}", lodgeDate),
                        string.Format("{0}", totalUnits),
                        string.Format("{0}", buyPlan),
                        string.Format("{0}", buyer)});
#line 213
  testRunner.And("In OLS05001 I continue with the following details:", ((string)(null)), table26, "And ");
#line 216
 testRunner.Then(string.Format("I should see the below ErrorMessage \"{0}\"", errorMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Testcase21470_MNYDN_ErrorValidation")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("OL_Online")]
        [NUnit.Framework.CategoryAttribute("ANZ_AUTO")]
        [NUnit.Framework.CategoryAttribute("21470")]
        [NUnit.Framework.CategoryAttribute("OL_DPM_DividendPlanMaintenance")]
        [NUnit.Framework.TestCaseAttribute("Test1", "MNYDN", "42428", "", "562000", "DRP1", "X0042573612", "There is not enough money for this holder.", null)]
        [NUnit.Framework.TestCaseAttribute("Test2", "MNYDN", "42428", "", "10", "DRP1", "X0055926867", "This holder does not have any money on this class.", null)]
        public virtual void Testcase21470_MNYDN_ErrorValidation(string test, string selCode, string transNumber, string lodgeDate, string totalUnits, string sellPlan, string seller, string errorMessage, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "OL_Online",
                    "ANZ_AUTO",
                    "21470",
                    "OL_DPM_DividendPlanMaintenance"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Testcase21470_MNYDN_ErrorValidation", @__tags);
#line 228
this.ScenarioSetup(scenarioInfo);
#line 230
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 231
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 232
  testRunner.And("In MNS00101 I click on: \"online data entry system\" within the System Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 233
  testRunner.And("In OLS00101 I Click on: \"dividend plan maintenance\" with in the online data entry" +
                    " system menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "SelCode"});
            table27.AddRow(new string[] {
                        string.Format("{0}", selCode)});
#line 234
  testRunner.And("In SELTRN20 I continue with the following details:", ((string)(null)), table27, "And ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "TransNumber",
                        "LodgeDate",
                        "TotalUnits",
                        "SellPlan",
                        "Seller"});
            table28.AddRow(new string[] {
                        string.Format("{0}", transNumber),
                        string.Format("{0}", lodgeDate),
                        string.Format("{0}", totalUnits),
                        string.Format("{0}", sellPlan),
                        string.Format("{0}", seller)});
#line 237
  testRunner.And("In OLS05101 I continue with the following details:", ((string)(null)), table28, "And ");
#line 240
 testRunner.Then(string.Format("I should see the below ErrorMessage \"{0}\"", errorMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Testcase21216_ELCIN_Transaction")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("OL_Online")]
        [NUnit.Framework.CategoryAttribute("ANZ_AUTO")]
        [NUnit.Framework.CategoryAttribute("21216")]
        [NUnit.Framework.CategoryAttribute("OL_DPM_DividendPlanMaintenance")]
        [NUnit.Framework.TestCaseAttribute("Test1", "ELCIN", "42429", "", "250", "LLM", "I0032794041", "EMPLOYEE LOAN LANDMARK MONEY", "26/08/2015", "C", "/LLM", "LLM/EMPLOYEE LOAN LANDMARK MONEY", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("Test2", "ELCIN", "42430", "", "561", "LAR", "I0030123603", "EMPLOYEE LOAN AU REFUND", "27/07/2015", "C", "/LAR", "LAR/EMPLOYEE LOAN AU REFUND", "*MR MONEY L/OVER 16/07/15        540.00    *MR MONEY L/OVER 19/07/15          32." +
            "00", "*MR MONEY L/OVER 27/07/15       1122.00", "**** Total for MONEY L/OVER          1694.00", "*MR 00000002     02/03/06          0.00", "**** Total for 00000002                 0.00", "", "", "", "", null)]
        public virtual void Testcase21216_ELCIN_Transaction(
                    string test, 
                    string selCode, 
                    string transNumber, 
                    string lodgeDate, 
                    string totalUnits, 
                    string buyClass, 
                    string buyer, 
                    string buyClassDesc, 
                    string buyDate, 
                    string action, 
                    string locateArgument, 
                    string certificateLine1, 
                    string certificateLine2, 
                    string certificateLine3, 
                    string certificateLine4, 
                    string certificateLine5, 
                    string certificateLine6, 
                    string certificateLine7, 
                    string certificateLine8, 
                    string certificateLine9, 
                    string certificateLine10, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "OL_Online",
                    "ANZ_AUTO",
                    "21216",
                    "OL_DPM_DividendPlanMaintenance"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Testcase21216_ELCIN_Transaction", @__tags);
#line 252
this.ScenarioSetup(scenarioInfo);
#line 254
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 255
 testRunner.When("In SELCOY01 I select the company: \"WES_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 256
  testRunner.And("In MNS00101 I click on: \"online data entry system\" within the System Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 257
  testRunner.And("In OLS00101 I Click on: \"dividend plan maintenance\" with in the online data entry" +
                    " system menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "SelCode"});
            table29.AddRow(new string[] {
                        string.Format("{0}", selCode)});
#line 258
  testRunner.And("In SELTRN20 I continue with the following details:", ((string)(null)), table29, "And ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "TransNumber",
                        "LodgeDate",
                        "TotalUnits",
                        "BuyClass",
                        "Buyer"});
            table30.AddRow(new string[] {
                        string.Format("{0}", transNumber),
                        string.Format("{0}", lodgeDate),
                        string.Format("{0}", totalUnits),
                        string.Format("{0}", buyClass),
                        string.Format("{0}", buyer)});
#line 261
  testRunner.And("In OLS05501 I continue with the following details:", ((string)(null)), table30, "And ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "BuyClass",
                        "BuyClassDesc",
                        "BuyDate",
                        "Buyer"});
            table31.AddRow(new string[] {
                        string.Format("{0}", buyClass),
                        string.Format("{0}", buyClassDesc),
                        string.Format("{0}", buyDate),
                        string.Format("{0}", buyer)});
#line 264
  testRunner.And("In OLS05502 I continue with the following details:", ((string)(null)), table31, "And ");
#line 267
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 268
 testRunner.When("In SELCOY01 I select the company: \"WES_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 269
  testRunner.And(string.Format("I go to the Enquiry system and Search {0}", buyer), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 270
  testRunner.And(string.Format("I enter the following details as the Locate action \"{0}\" \"{1}\"", action, locateArgument), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "CertificateLine1",
                        "CertificateLine2",
                        "CertificateLine3",
                        "CertificateLine4",
                        "CertificateLine5",
                        "CertificateLine6",
                        "CertificateLine7",
                        "CertificateLine8",
                        "CertificateLine9",
                        "CertificateLine10"});
            table32.AddRow(new string[] {
                        string.Format("{0}", certificateLine1),
                        string.Format("{0}", certificateLine2),
                        string.Format("{0}", certificateLine3),
                        string.Format("{0}", certificateLine4),
                        string.Format("{0}", certificateLine5),
                        string.Format("{0}", certificateLine6),
                        string.Format("{0}", certificateLine7),
                        string.Format("{0}", certificateLine8),
                        string.Format("{0}", certificateLine9),
                        string.Format("{0}", certificateLine10)});
#line 271
 testRunner.Then("In ENS01012 I should see Register details as:", ((string)(null)), table32, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
