// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SCRIPAU.Automation.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("OL_ST_SessionTotals")]
    public partial class OL_ST_SessionTotalsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "OL_ST_SessionTotals.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "OL_ST_SessionTotals", "Ensure OL_ST_SessionTotals Transaction functionality covered", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TestCase 34645 Session Totals Verify Run Status Enquiry")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("OL_Online")]
        [NUnit.Framework.CategoryAttribute("CPU_AUTO")]
        [NUnit.Framework.CategoryAttribute("32413")]
        [NUnit.Framework.CategoryAttribute("OL_ST_SessionTotals")]
        [NUnit.Framework.CategoryAttribute("FullSmokeTest")]
        [NUnit.Framework.TestCaseAttribute("Test1", "ST", "r", "", "001", "", "", "002", "", "STONES - GEN REINVESTMENT", "", "", "STONES ANZSEC BRK FRM REINVEST", "", "Start of run.>", "Current......>", "Issued Capital", "Start of run.>", "Current......>", "00000000    (NS)      (NS)", "00000000    (NS)      (NS)", "0", "00000000    (NS)      (NS)", "00000000    (NS)      (NS)", "", null)]
        public virtual void TestCase34645SessionTotalsVerifyRunStatusEnquiry(
                    string test, 
                    string selection, 
                    string option, 
                    string runDate1, 
                    string class1, 
                    string class2, 
                    string class3, 
                    string class4, 
                    string class5, 
                    string desc1, 
                    string desc2, 
                    string desc3, 
                    string desc4, 
                    string desc5, 
                    string constant11, 
                    string constant12, 
                    string constant13, 
                    string constant14, 
                    string constant15, 
                    string ranges1, 
                    string ranges2, 
                    string ranges3, 
                    string ranges4, 
                    string ranges5, 
                    string sessionNumber, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "OL_Online",
                    "CPU_AUTO",
                    "32413",
                    "OL_ST_SessionTotals",
                    "FullSmokeTest"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TestCase 34645 Session Totals Verify Run Status Enquiry", @__tags);
#line 10
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
  testRunner.And("In MNS00101 I click on: \"online data entry system\" within the System Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Selection"});
            table1.AddRow(new string[] {
                        string.Format("{0}", selection)});
#line 15
  testRunner.And("IN OLS00101 I continue with the following details:", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Option",
                        "SessionNumber"});
            table2.AddRow(new string[] {
                        string.Format("{0}", option),
                        string.Format("{0}", sessionNumber)});
#line 18
  testRunner.And("IN SESTOT01 I continue with the following details:", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "RunDate1",
                        "Class1",
                        "Class2",
                        "Class3",
                        "Class4",
                        "Class5",
                        "Desc1",
                        "Desc2",
                        "Desc3",
                        "Desc4",
                        "Desc5",
                        "Constant11",
                        "Constant12",
                        "Constant13",
                        "Constant14",
                        "Constant15",
                        "Ranges1",
                        "Ranges2",
                        "Ranges3",
                        "Ranges4",
                        "Ranges5"});
            table3.AddRow(new string[] {
                        string.Format("{0}", runDate1),
                        string.Format("{0}", class1),
                        string.Format("{0}", class2),
                        string.Format("{0}", class3),
                        string.Format("{0}", class4),
                        string.Format("{0}", class5),
                        string.Format("{0}", desc1),
                        string.Format("{0}", desc2),
                        string.Format("{0}", desc3),
                        string.Format("{0}", desc4),
                        string.Format("{0}", desc5),
                        string.Format("{0}", constant11),
                        string.Format("{0}", constant12),
                        string.Format("{0}", constant13),
                        string.Format("{0}", constant14),
                        string.Format("{0}", constant15),
                        string.Format("{0}", ranges1),
                        string.Format("{0}", ranges2),
                        string.Format("{0}", ranges3),
                        string.Format("{0}", ranges4),
                        string.Format("{0}", ranges5)});
#line 21
  testRunner.And("IN RUNSTS01 I continue with the following details:", ((string)(null)), table3, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TestCase 34646 Sessions Total Select a Session Number")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("OL_Online")]
        [NUnit.Framework.CategoryAttribute("CPU_AUTO")]
        [NUnit.Framework.CategoryAttribute("32413")]
        [NUnit.Framework.CategoryAttribute("OL_ST_SessionTotals")]
        [NUnit.Framework.TestCaseAttribute("Test1", "ST", "s", "0099", null)]
        [NUnit.Framework.TestCaseAttribute("Test2", "ST", "s", "0141", null)]
        [NUnit.Framework.TestCaseAttribute("Test3", "ST", "s", "2244", null)]
        [NUnit.Framework.TestCaseAttribute("Test4", "ST", "s", "0551", null)]
        public virtual void TestCase34646SessionsTotalSelectASessionNumber(string test, string selection, string option, string sessionNumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "OL_Online",
                    "CPU_AUTO",
                    "32413",
                    "OL_ST_SessionTotals"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TestCase 34646 Sessions Total Select a Session Number", @__tags);
#line 34
this.ScenarioSetup(scenarioInfo);
#line 36
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
  testRunner.And("In MNS00101 I click on: \"online data entry system\" within the System Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Selection"});
            table4.AddRow(new string[] {
                        string.Format("{0}", selection)});
#line 39
  testRunner.And("IN OLS00101 I continue with the following details:", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Option",
                        "SessionNumber"});
            table5.AddRow(new string[] {
                        string.Format("{0}", option),
                        string.Format("{0}", sessionNumber)});
#line 42
  testRunner.And("IN SESTOT01 I continue with the following details:", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "SessionNumber"});
            table6.AddRow(new string[] {
                        string.Format("{0}", sessionNumber)});
#line 45
  testRunner.And("IN SESTOT01 I verify the following details:", ((string)(null)), table6, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Case 35090 Sessions Total Verify error")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("OL_Online")]
        [NUnit.Framework.CategoryAttribute("CPU_AUTO")]
        [NUnit.Framework.CategoryAttribute("35090")]
        [NUnit.Framework.CategoryAttribute("OL_ST_SessionTotals")]
        [NUnit.Framework.TestCaseAttribute("Test1", "ST", "d", "0044", "There are NO records on file for", null)]
        public virtual void TestCase35090SessionsTotalVerifyError(string test, string selection, string option, string sessionNumber, string errorMessage, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "OL_Online",
                    "CPU_AUTO",
                    "35090",
                    "OL_ST_SessionTotals"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Case 35090 Sessions Total Verify error", @__tags);
#line 61
this.ScenarioSetup(scenarioInfo);
#line 63
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 64
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
  testRunner.And("In MNS00101 I click on: \"online data entry system\" within the System Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Selection"});
            table7.AddRow(new string[] {
                        string.Format("{0}", selection)});
#line 66
  testRunner.And("IN OLS00101 I continue with the following details:", ((string)(null)), table7, "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Option",
                        "SessionNumber"});
            table8.AddRow(new string[] {
                        string.Format("{0}", option),
                        string.Format("{0}", sessionNumber)});
#line 69
  testRunner.And("IN SESTOT01 I continue with the following details:", ((string)(null)), table8, "And ");
#line 72
 testRunner.Then(string.Format("I should see the below ErrorMessage \"{0}\"", errorMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TestCase 34648 Display Session Totals")]
        [NUnit.Framework.CategoryAttribute("winformsTest")]
        [NUnit.Framework.CategoryAttribute("OL_Online")]
        [NUnit.Framework.CategoryAttribute("CPU_AUTO")]
        [NUnit.Framework.CategoryAttribute("34648")]
        [NUnit.Framework.CategoryAttribute("OL_ST_SessionTotals")]
        [NUnit.Framework.CategoryAttribute("FullSmokeTest")]
        [NUnit.Framework.TestCaseAttribute("Test1", "ST", "s", "0014", "F", "", "U", "NA", "M", "42338", "Display Session Totals", "d", "RXAUD", "NAME & ADDRESS (AUDIT MODIFY)", "", "1", "", "End of transactions", "", "1", null)]
        public virtual void TestCase34648DisplaySessionTotals(
                    string test, 
                    string selection, 
                    string option, 
                    string sessionNumber, 
                    string action, 
                    string updateOption, 
                    string action1, 
                    string updateOption1, 
                    string action3, 
                    string transNbrI, 
                    string hnaLineCh1To30R, 
                    string option1, 
                    string transCode1, 
                    string transDesc1, 
                    string units1, 
                    string entries1, 
                    string transCode2, 
                    string transDesc2, 
                    string units2, 
                    string entries2, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "winformsTest",
                    "OL_Online",
                    "CPU_AUTO",
                    "34648",
                    "OL_ST_SessionTotals",
                    "FullSmokeTest"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TestCase 34648 Display Session Totals", @__tags);
#line 84
this.ScenarioSetup(scenarioInfo);
#line 86
 testRunner.Given("I have connected to WinForms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 87
 testRunner.When("In SELCOY01 I select the company: \"ANZ_AUTO\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
  testRunner.And("In MNS00101 I click on: \"online data entry system\" within the System Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Selection"});
            table9.AddRow(new string[] {
                        string.Format("{0}", selection)});
#line 89
  testRunner.And("IN OLS00101 I continue with the following details:", ((string)(null)), table9, "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Option",
                        "SessionNumber"});
            table10.AddRow(new string[] {
                        string.Format("{0}", option),
                        string.Format("{0}", sessionNumber)});
#line 92
  testRunner.And("IN SESTOT01 I continue with the following details:", ((string)(null)), table10, "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "SessionNumber"});
            table11.AddRow(new string[] {
                        string.Format("{0}", sessionNumber)});
#line 95
  testRunner.And("IN SESTOT01 I verify the following details:", ((string)(null)), table11, "And ");
#line 98
  testRunner.And("I PressESC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
  testRunner.And("In OLS00101 I Click on: \"static detail\" with in the online data entry system menu" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
  testRunner.And(string.Format("In OLS01101 I enter following details as the update option \"{0}\" \"{1}\"", action, updateOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 101
  testRunner.And(string.Format("In OLS01102 I enter following details as the update option \"{0}\" \"{1}\"", action1, updateOption1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Action3",
                        "TransNbrI",
                        "HnaLineCh1to30R"});
            table12.AddRow(new string[] {
                        string.Format("{0}", action3),
                        string.Format("{0}", transNbrI),
                        string.Format("{0}", hnaLineCh1To30R)});
#line 102
  testRunner.And("In OLS01201 I Change Holder Name as:", ((string)(null)), table12, "And ");
#line 105
  testRunner.And("I PressESC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
  testRunner.And("I PressESC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Selection"});
            table13.AddRow(new string[] {
                        string.Format("{0}", selection)});
#line 107
  testRunner.And("IN OLS00101 I continue with the following details:", ((string)(null)), table13, "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Option",
                        "SessionNumber"});
            table14.AddRow(new string[] {
                        string.Format("{0}", option1),
                        string.Format("{0}", sessionNumber)});
#line 110
  testRunner.And("IN SESTOT01 I continue with the following details:", ((string)(null)), table14, "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "TransCode1",
                        "TransDesc1",
                        "Units1",
                        "Entries1",
                        "TransCode2",
                        "TransDesc2",
                        "Units2",
                        "Entries2"});
            table15.AddRow(new string[] {
                        string.Format("{0}", transCode1),
                        string.Format("{0}", transDesc1),
                        string.Format("{0}", units1),
                        string.Format("{0}", entries1),
                        string.Format("{0}", transCode2),
                        string.Format("{0}", transDesc2),
                        string.Format("{0}", units2),
                        string.Format("{0}", entries2)});
#line 113
  testRunner.And("IN SESTOT02 I verify with the following details:", ((string)(null)), table15, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
