
Feature: TS_TradingSystemReports

@AESSPlanSales
@TFS538234
@TS_TradingSystemGold
@30108
Scenario Outline: Deferred Real Time Sale EndtoEnd
	Given I have connected to WinForms
	When In SELCOY01 I select the company as "<COY>"
		#And I go to "Company Options" Control Code Menu
		#And In HKS01516 I set the Multi-Cert Flag to "<Multi-Cert>"
		And I go to "Trading Control Codes" Control Code Menu
		And In TRD24000 I select the Trade Control Code "<tradeControlCode>"
		And In TRD24001 I perform a Change for On Market Trade "<OnMarketTrade>", "<BrokerCode>", "<BrokerAccountID>", "<ConnectionCode>", "<RealTimeTrading>" and Top Up "<TopupPercentage>", "<SellSelected>" and Remaining Balance Options "<Option>", "<TranType>", "<Class>", "<Reg>" and World Link Number "<WorldLinkNumber>"
		And I go to the Trading system Sales and trade control code "<tradeControlCode>"
		And In TRS00501 I Add Postal Transaction Entry details as "<SearchName>" 
		And In TRS00502 I Add Postal Transaction Entry details as "<SellOption>" "<Units>" "<PaymentMethod>" "<PrefCurrency>" "<NotificationReqdInd>" "<Balance>" "<AvailBalance>"	
		And In TRS00507 I Add Postal Transaction Entry details as "<SellAll01>" "<Units01>" "<SellAll02>" "<Units02>" "<SellAll03>" "<Units03>" "<SellAll04>" "<Units04>" "<SellAll05>" "<Units05>" "<SellAll06>" "<Units06>" "<SellAll07>" "<Units07>" "<SellAll08>" "<Units08>" "<SellAll09>" "<Units09>"
		And In TRS00511 I Add Postal Transaction Entry details as "<DurationType>" "<EstMarketValue>"
		And In TRS00513 I Add Postal Transaction Entry details as "<Cover01>" "<Cover02>" "<Cover03>" "<Cover04>" "<Cover05>" "<Cover06>" "<Cover07>" "<Cover08>" "<Cover09>" "<Cover10>" "<Cover11>" "<Cover12>" "<Cover13>" "<Cover14>" "<Cover15>"
		And In TRS00504 I Verify Postal Transaction Entry details as "<UnitsSell>" "<EstMarketValue>" "<MarketValue>" "<PurchResidueAmt>" "<FederalTaxWithheld>" "<LoanAmt>" "<ChargeAmount1>" "<ChargeAmount2>" "<ChargeAmount3>" "<TotalGst>" "<EstimatedProceeds>"
		And In TRS00512 I Add Postal Transaction Entry details as "<OverrideEmailInd>" "<EmailAddress>"
		And In TRS00503 I Add Postal Transaction Entry details as "<ConfirmUnits>" "<ConfirmWarningFlag5>"
		And In TRD00401 I Change Order Status to "<MenuSelection>" "<ConfirmStatus>" "<TradeDate>" "<TradeTimeHH>" "<TradeTimeMM>" "<SettlementDate>" "<FinalPrice>"
	Then In TRD004CS I Verify Change Order Status details1 as "<UnitsTraded>" "<TotalCost>" "<FinalPrice>" "<TradePrice>" "<PriceATAudit>" "<GrossAmount>" "<PurchaseResidue>" "<HolderCharges1>" "<LoanAmount>" "<OptionCost>" "<Gst>" "<TaxWithheld>" "<NettAmount>" "<ChargeAmount01>" "<ChargeAmount02>" "<ChargeAmount03>" "<ChargeAmount04>" "<ChargeAmount05>" "<ChargeAmount06>"
		And In TRD004CS I Verify Change Order Status details2 as "<LocalChqCount>" "<LocalChqNettAmount>" "<ForeignChqCount>" "<ForeignChqNettAmt>" "<WireCount>" "<WireNettAmount>" "<DirectBankingCount>" "<DirectBankNettAmt>" "<EmployerCount>" "<EmployerNettAmount>" "<CompanyCharges>" "<CompanyTax>" "<HolderCharges>" "<HolderTax>" "<ReportCharges>" "<ReportTax>" "<BankType>" "<BranchNumber>" "<AccountNumber>"
	When In TRD00101 I Run the Generate Output Job as "<PaymentAccount1>" "<OrderNO>" "<Ident>" "<ClassCode>" "<NbrTrades>" "<TradeGrossAmount>" "<TradeFrom>" "<TradeTO>" "<SettlementFrom>" "<SettlementTO>"
		And I wait for  GenerateOutput job to complete
			| PassCriteria | timeout | FailCriteria | PassCriteriaLNX | FailCriteriaLNX |
			| completion   | 240     | error        | DONE            | EXIT            |
		And In TRD00401 I Force Settle the Order as "<MenuSelection1>" "<ConfirmStatus1>"
	Then In TRS01010 I Verify Transaction Enquiry details as "<TradingID>" "<Status>" "<Price>" "<ClassCode>" "<TransCount>" "<TransTotal>" "<MoneyTotal>" "<SettlementDate>" "<ApplyTaxInd>" "<PaymentMethod>" "<PaymentMethodDesc>" "<Currency>" "<SellUnits>" "<OrderType>" "<TradeUnits>" "<TransMoney>"
		And In TRDSCH02 I Verify Transaction Enquiry details as "<TradingID>" "<BulkType>" "<BulkTypeDesc>" "<StatusDesc>" "<TotalCount>" "<OrderTransUnits>" "<TotalMoney>" "<TradeDate>" "<ReqdSettlementDate>" "<ActualSettlementDate>" "<FinalPrice>" "<ReconciliationCode>" "<CshtrnReference>" "<MinimumDeal>" "<MaximumDeal>" "<CutOffTime>" "<CounterpartyClass>" "<CounterRegisterCode>" "<OrderType1>"
		And In TRDSCHCS I Verify Transaction Enquiry details1 as "<UnitsTraded>" "<TotalCost>" "<FinalPrice>" "<PriceATAudit>" "<GrossAmount>" "<PurchaseResidue>" "<HolderCharges1>" "<LoanAmount>" "<OptionCost>" "<Gst>" "<TaxWithheld>" "<NettAmount>" "<ChargeAmount01>" "<ChargeAmount02>" "<ChargeAmount03>" "<ChargeAmount04>" "<ChargeAmount05>" "<ChargeAmount06>"
		And In TRDSCHCS I Verify Transaction Enquiry details2 as "<LocalChqCount>" "<LocalChqNettAmount>" "<ForeignChqCount>" "<ForeignChqNettAmt>" "<WireCount>" "<WireNettAmount>" "<DirectBankingCount>" "<DirectBankNettAmt>" "<EmployerCount>" "<EmployerNettAmount>" "<CompanyCharges>" "<CompanyTax>" "<HolderCharges>" "<HolderTax>" "<ReportCharges>" "<ReportTax>" "<BankType>" "<BranchNumber>" "<AccountNumber>"
		And I go the Main Menu From Trading System
	#Given I have connected to WinForms
	When In SELCOY01 I select the company as "<COY>"
		And I go to the Enquiry system and Search <SearchName>
		And I enter the following details as the Locate action:
				| Field           | Value |
				| Action          | TH    |
				| Locate Argument | /ATS  |	 
	Then In ENSTRD48 I should see trading history summary as "<Line1>" "<Line2>" "<Line3>" "<Line4>" "<Line5>"	
	When I enter the following details as the locatActions "<Action>"  "<LocateArgument>"
		And In ENSTRDSH I Verify Trade History details1 as "<Units1>" "<UnitsSell>" "<FinalPrice>" "<GrossAmount>" "<PurchaseResidue>" "<LoanAmount>" "<OptionCost>" "<Gst>" "<TaxWithheld>" "<NettAmount>" "<ChargeAmount01>" "<ChargeAmount02>" "<ChargeAmount03>" "<ChargeAmount04>" "<ChargeAmount05>" "<ChargeAmount06>" "<PaymentDate>" "<PaymentAccount>" 
		And In ENSTRDSH I Verify Trade History details2 as "<PrefCurrency>" "<CurrencyDesc>" "<PaymentMethod1>" "<HolderCharges>" "<HolderTax>" "<CompanyCharges>" "<CompanyTax>" "<ReportCharges>" "<ReportTax>" "<TotalCharges>" "<GstTaxTotal>" "<BankCode>" "<PayeeAccountNumber>" "<AccountName>" "<RemainingBalance>" "<RemBalIndDesc>" "<TransfereeHolder>" "<TransfereeClass>"
	Then I copy output files to local
		| ReportHeading   | FileName | COY   | CurrentCOY   |
		| <ReportHeading> |          | <COY> | <CurrentCOY> |
		And I parse the files from VMS or Linux
		And I compare the files from VMS and Linux goldcopy

Examples: 
		| ReportHeading | COY       | OnMarketTrade | BrokerCode | BrokerAccountID | ConnectionCode | RealTimeTrading | TopupPercentage | SellSelected | Option | TranType | Class | Reg | WorldLinkNumber | SearchName  | SellOption | Units | PaymentMethod | PrefCurrency | NotificationReqdInd | Balance   | AvailBalance | DurationType | EstMarketValue | UnitsSell | MarketValue | PurchResidueAmt | FederalTaxWithheld | LoanAmt | ChargeAmount1 | ChargeAmount2 | ChargeAmount3 | TotalGst | EstimatedProceeds | OverrideEmailInd | EmailAddress                            | ConfirmUnits | ConfirmWarningFlag5 | MenuSelection | ConfirmStatus | TradeDate  | TradeTimeHH | TradeTimeMM | SettlementDate | TotalUnits | UnitsTraded | TotalCost | FinalPrice | TradePrice | PriceATAudit | GrossAmount | PurchaseResidue | HolderCharges1 | LoanAmount | OptionCost | Gst   | TaxWithheld | NettAmount | ChargeAmount01 | ChargeAmount02 | ChargeAmount03 | ChargeAmount04 | ChargeAmount05 | ChargeAmount06 | LocalChqCount | LocalChqNettAmount | ForeignChqCount | ForeignChqNettAmt | WireCount | WireNettAmount | DirectBankingCount | DirectBankNettAmt | EmployerCount | EmployerNettAmount | CompanyCharges | CompanyTax | HolderCharges | HolderTax | ReportCharges | ReportTax | PaymentAccount | BankType | BranchNumber | AccountNumber | PaymentAccount1 | OrderNO | Ident | ClassCode | NbrTrades | TradeGrossAmount | TradeFrom | TradeTO | SettlementFrom | SettlementTO | MenuSelection1 | ConfirmStatus1 | TradingID | Status  | Price     | TransCount | TransTotal | MoneyTotal | ApplyTaxInd | PaymentMethodDesc | Currency | SellUnits | OrderType | BulkType | BulkTypeDesc | StatusDesc | TotalCount | OrderTransUnits | TotalMoney | ReqdSettlementDate | ActualSettlementDate | ReconciliationCode | CshtrnReference | MinimumDeal | MaximumDeal        | CutOffTime | CounterpartyClass | CounterRegisterCode | OrderType1 | Line1                                                                                            | Line2 | Line3 | Line4 | Line5 | Action | LocateArgument | PaymentDate | CurrencyDesc      | PaymentMethod1 | TotalCharges | GstTaxTotal | BankCode | PayeeAccountNumber | AccountName | Cover01 | Cover02 | Cover03 | Cover04 | Cover05 | Cover06 | Cover07 | Cover08 | Cover09 | Cover10 | Cover11 | Cover12 | Cover13 | Cover14 | Cover15 | Units1    | SellAll01 | Units01 | SellAll02 | Units02 | SellAll03 | Units03 | SellAll04 | Units04 | SellAll05 | Units05 | SellAll06 | Units06 | SellAll07 | Units07 | SellAll08 | Units08 | SellAll09 | Units09 | RemainingBalance | RemBalIndDesc | TransfereeHolder | TransfereeClass | tradeControlCode | TradeUnits | TransMoney | CurrentCOY |
		| SellAll       | NAB2_AUTO | M             | 3383       | CLS.GAP         | ORMSAUUAT      | Y               | 0.00            | Y            | C      | ESTSC    | ORD   | VIC | 123451234       | I0032187749 | A          |       | C             | AUD          | E                   | 73.000000 | 73.000000    | 1            | 30.00          | 73.000000 | 2190.00     |                 |                    |         | 6.57          | 100.00        | 15.00         | 10.66    | 2057.77           | N                | CIFAH.K.KLUPPUR._test@computershare.com | 73.000000    | Y                   | C             | C             | 20/08/2015 | 10          | 00          | 20/08/2015     | 73.000000  | 73.000000   | 2190.00   | 30.000000  | 30.000000  | 30.000000    | 2190.00     |                 | 121.57         |            |            | 10.66 |             | 2057.77    | 6.57           | 100.00         |                |                | 15.00          |                | 1             | 2057.77            |                 |                   |           |                |                    |                   |               |                    |                |            | 121.57        | 10.66     |               |           |                |          |              |               | TSSAL           | ATS1    | NDF   | ATS       | 1         | 73.000000        |           |         | 20/08/2015     | 20/08/2015   | S              | S              |           | Settled | 30.000000 | 1          | 73.000000  | 2057.77    | Y           | Cheque Loc        | AUD      | 73.000000 | Sell All  | S        | SALE         | Settled    | 1          | 73.000000       | 2057.77    | 20/08/2015         | 20/08/2015           | ESSOPT             | 1501            | 1.000000    | 99999999999.000000 | 10:00      | ORD               | VIC                 | Market     | ATS Sale     ATSR0000002  79268996 20/08/15 Set           73.000000       2057.77      30.000000 |       |       |       |       | 01     |                | 20/08/2015  | AUSTRALIAN DOLLAR | Cheque/Unpres  | 121.57       | 10.66       |          |                    |             |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         | 73.000000 |           |         |           |         |           |         |           |         |           |         |           |         |           |         |           |         |           |         |                  |               |                  |                 | ATSR             | 73.000000  | 2057.77    | NAB2_AUTO  |


@TS_TradingSystemGold
@OptionsPlanSales
@30522
Scenario Outline: Options Real Time Sale EndtoEnd
	Given I have connected to WinForms
	When In SELCOY01 I select the company as "<COY>"
		And I go to "Company Options" Control Code Menu
		And In HKS01516 I set the Multi-Cert Flag to "<Multi-Cert>"
		And I go to "Trading Control Codes" Control Code Menu
		And In TRD24000 I select the Trade Control Code "<tradeControlCode>"
		And In TRD24001 I perform a Change for On Market Trade "<OnMarketTrade>", "<BrokerCode>", "<BrokerAccountID>", "<ConnectionCode>", "<RealTimeTrading>" and Top Up "<TopupPercentage>", "<SellSelected>" and Remaining Balance Options "<Option>", "<TranType>", "<Class>", "<Reg>" and World Link Number "<WorldLinkNumber>"
		And I go to the Trading system Sales and trade control code "<tradeControlCode>"
		And In TRS00701 I Add Postal Transaction Entry details as "<TransNumber>" "<SearchName>" 
	#Then In TRS00711 I Verify Certificate Selection details as "<CertID1>" "<Register1>" "<OptionPrice1>" "<CertBalance1>" "<AvailBal1>" "<CertID2>" "<Register2>" "<OptionPrice2>" "<CertBalance2>" "<AvailBal2>"
	When In TRS00702 I Add Postal Transaction Entry details as "<SellOption>" "<RemainingBalInd>" "<PaymentMethod>" "<PrefCurrency>" "<NotificationReqdInd>" "<Balance>" "<AvailBalance>"		
		And In TRS00707 I Add Postal Transaction Entry details as "<SellAll01>" "<ExerciseUnits01>" "<Units01>" "<SellAll02>" "<ExerciseUnits02>" "<Units02>" "<SellAll03>" "<ExerciseUnits03>" "<Units03>" "<SellAll04>" "<ExerciseUnits04>" "<Units04>"
		And In TRS00511 I Add Postal Transaction Entry details as "<DurationType>" "<EstMarketValue>"
		And In TRS00704 I Verify Postal Transaction Entry details as "<UnitsExercise>" "<UnitsSell>" "<EstMarketValue>" "<MarketValue>" "<PurchResidueAmt>" "<FederalTaxWithheld>" "<OptionCost>" "<ChargeAmount1>" "<ChargeAmount2>" "<ChargeAmount3>" "<TotalGst>" "<EstimatedProceeds>"
		And In TRS00703 I Add Postal Transaction Entry details as "<ExerciseUnits>" "<ConfirmUnits>" "<ConfirmWarningFlag5>"
		And In TRD00401 I Change Order Status to "<MenuSelection>" "<ConfirmStatus>" "<TradeDate>" "<TradeTimeHH>" "<TradeTimeMM>" "<SettlementDate>" "<FinalPrice>"
	Then In TRD004CS I Verify Change Order Status details1 as "<UnitsTraded>" "<TotalCost>" "<FinalPrice>" "<TradePrice>" "<PriceATAudit>" "<GrossAmount>" "<PurchaseResidue>" "<HolderCharges1>" "<LoanAmount>" "<OptionCost>" "<Gst>" "<TaxWithheld>" "<NettAmount>" "<ChargeAmount01>" "<ChargeAmount02>" "<ChargeAmount03>" "<ChargeAmount04>" "<ChargeAmount05>" "<ChargeAmount06>"
		And In TRD004CS I Verify Change Order Status details2 as "<LocalChqCount>" "<LocalChqNettAmount>" "<ForeignChqCount>" "<ForeignChqNettAmt>" "<WireCount>" "<WireNettAmount>" "<DirectBankingCount>" "<DirectBankNettAmt>" "<EmployerCount>" "<EmployerNettAmount>" "<CompanyCharges>" "<CompanyTax>" "<HolderCharges>" "<HolderTax>" "<ReportCharges>" "<ReportTax>" "<BankType>" "<BranchNumber>" "<AccountNumber>"
	When In TRD00101 I Run the Generate Output Job as "<PaymentAccount1>" "<OrderNO>" "<Ident>" "<ClassCode>" "<NbrTrades>" "<TradeGrossAmount>" "<TradeFrom>" "<TradeTO>" "<SettlementFrom>" "<SettlementTO>"
		And I wait for  GenerateOutput job to complete
			| PassCriteria | timeout | FailCriteria | PassCriteriaLNX | FailCriteriaLNX |
			| completion   | 240     | error        | DONE            | EXIT            |		
		And In TRD00401 I Apply Exercise Transaction as "<MenuSelection2>" "<ConfirmStatus2>" "<TradeDate>" "<TradeTimeHH>" "<TradeTimeMM>" "<SettlementDate>" "<FinalPrice>"
		And In TRD00401 I Force Settle the Order as "<MenuSelection1>" "<ConfirmStatus1>"
	Then In TRS01010 I Verify Transaction Enquiry details as "<TradingID>" "<Status>" "<Price>" "<ClassCode>" "<TransCount>" "<TransTotal>" "<MoneyTotal>" "<SettlementDate>" "<ApplyTaxInd>" "<PaymentMethod>" "<PaymentMethodDesc>" "<Currency>" "<SellUnits>" "<OrderType>" "<TradeUnits>" "<TransMoney>"
		And In TRDSCH02 I Verify Transaction Enquiry details as "<TradingID>" "<BulkType>" "<BulkTypeDesc>" "<StatusDesc>" "<TotalCount>" "<OrderTransUnits>" "<TotalMoney>" "<TradeDate>" "<ReqdSettlementDate>" "<ActualSettlementDate>" "<FinalPrice>" "<ReconciliationCode>" "<CshtrnReference>" "<MinimumDeal>" "<MaximumDeal>" "<CutOffTime>" "<CounterpartyClass>" "<CounterRegisterCode>" "<OrderType1>"
		And In TRDSCHCS I Verify Transaction Enquiry details1 as "<UnitsTraded>" "<TotalCost>" "<FinalPrice>" "<PriceATAudit>" "<GrossAmount>" "<PurchaseResidue>" "<HolderCharges1>" "<LoanAmount>" "<OptionCost>" "<Gst>" "<TaxWithheld>" "<NettAmount>" "<ChargeAmount01>" "<ChargeAmount02>" "<ChargeAmount03>" "<ChargeAmount04>" "<ChargeAmount05>" "<ChargeAmount06>"
		And In TRDSCHCS I Verify Transaction Enquiry details2 as "<LocalChqCount>" "<LocalChqNettAmount>" "<ForeignChqCount>" "<ForeignChqNettAmt>" "<WireCount>" "<WireNettAmount>" "<DirectBankingCount>" "<DirectBankNettAmt>" "<EmployerCount>" "<EmployerNettAmount>" "<CompanyCharges>" "<CompanyTax>" "<HolderCharges>" "<HolderTax>" "<ReportCharges>" "<ReportTax>" "<BankType>" "<BranchNumber>" "<AccountNumber>"
		And I go the Main Menu From Trading System
	#Given I have connected to WinForms
	When In SELCOY01 I select the company as "<COY>"
		And I go to the Enquiry system and Search <SearchName>
		And I enter the following details as the locatActions "<Action1>"  "<LocateArgument1>"
	Then In ENSTRD48 I should see trading history summary as "<Line1>" "<Line2>" "<Line3>" "<Line4>" "<Line5>"	
	When I enter the following details as the locatActions "<Action>"  "<LocateArgument>"
		And In ENSTRDSH I Verify Trade History details1 as "<OrderTransUnits>" "<UnitsSell>" "<FinalPrice>" "<GrossAmount>" "<PurchaseResidue>" "<LoanAmount>" "<OptionCost>" "<Gst>" "<TaxWithheld>" "<NettAmount>" "<ChargeAmount01>" "<ChargeAmount02>" "<ChargeAmount03>" "<ChargeAmount04>" "<ChargeAmount05>" "<ChargeAmount06>" "<PaymentDate>" "<PaymentAccount>" 
		And In ENSTRDSH I Verify Trade History details2 as "<PrefCurrency>" "<CurrencyDesc>" "<PaymentMethod1>" "<HolderCharges>" "<HolderTax>" "<CompanyCharges>" "<CompanyTax>" "<ReportCharges>" "<ReportTax>" "<TotalCharges>" "<GstTaxTotal>" "<BankCode>" "<PayeeAccountNumber>" "<AccountName>" "<RemainingBalance>" "<RemBalIndDesc>" "<TransfereeHolder>" "<TransfereeClass>"
	Then I copy output files to local
		| ReportHeading   | FileName | COY   | CurrentCOY   |
		| <ReportHeading> |          | <COY> | <CurrentCOY> |
		And I parse the files from VMS or Linux
		And I compare the files from VMS and Linux goldcopy



Examples: 
		| ReportHeading | COY       | Multi-Cert | OnMarketTrade | BrokerCode | BrokerAccountID | ConnectionCode | RealTimeTrading | TopupPercentage | SellSelected | Option | TranType | Class | Reg | WorldLinkNumber | TransNumber | SearchName  | SellAll01 | ExerciseUnits01 | Units01 | SellAll02 | ExerciseUnits02 | Units02 | SellAll03 | ExerciseUnits03 | Units03 | SellAll04 | ExerciseUnits04 | Units04 | SellOption | RemainingBalInd | PaymentMethod | PrefCurrency | NotificationReqdInd | Balance     | AvailBalance | DurationType | EstMarketValue | UnitsExercise | UnitsSell   | MarketValue | PurchResidueAmt | FederalTaxWithheld | OptionCost | LoanAmt | ChargeAmount1 | ChargeAmount2 | ChargeAmount3 | TotalGst | EstimatedProceeds | ConfirmUnits | ConfirmWarningFlag5 | MenuSelection | ConfirmStatus | TradeDate  | TradeTimeHH | TradeTimeMM | SettlementDate | TotalUnits  | UnitsTraded | TotalCost | FinalPrice | TradePrice | PriceATAudit | GrossAmount | PurchaseResidue | HolderCharges1 | LoanAmount | Gst   | TaxWithheld | NettAmount | ChargeAmount01 | ChargeAmount02 | ChargeAmount03 | ChargeAmount04 | ChargeAmount05 | ChargeAmount06 | LocalChqCount | LocalChqNettAmount | ForeignChqCount | ForeignChqNettAmt | WireCount | WireNettAmount | DirectBankingCount | DirectBankNettAmt | EmployerCount | EmployerNettAmount | CompanyCharges | CompanyTax | HolderCharges | HolderTax | ReportCharges | ReportTax | PaymentAccount | BankType | BranchNumber | AccountNumber | PaymentAccount1 | OrderNO | Ident | ClassCode | NbrTrades | TradeGrossAmount | TradeFrom | TradeTO | SettlementFrom | SettlementTO | MenuSelection1 | ConfirmStatus1 | TradingID | Status  | Price     | TransCount | TransTotal  | MoneyTotal | ApplyTaxInd | PaymentMethodDesc | Currency | SellUnits   | OrderType | BulkType | BulkTypeDesc | StatusDesc | TotalCount | OrderTransUnits | TotalMoney | ReqdSettlementDate | ActualSettlementDate | ReconciliationCode | CshtrnReference | MinimumDeal | MaximumDeal        | CutOffTime | CounterpartyClass | CounterRegisterCode | OrderType1 | Line1 | Line2 | Line3 | Line4 | Line5 | Action | LocateArgument | PaymentDate | CurrencyDesc      | PaymentMethod1 | TotalCharges | GstTaxTotal | MenuSelection2 | ConfirmStatus2 | Action1 | LocateArgument1 | BankCode | PayeeAccountNumber | AccountName | RemainingBalance | RemBalIndDesc | TransfereeHolder | TransfereeClass | tradeControlCode | TradeUnits  | TransMoney | CurrentCOY |
		| ExerciseAll   | NAB2_AUTO | N          | M             | 3383       | CLS.GAP         | ORMSAUUAT      | Y               | 0.00            |              | C      | ESOXR    | ORD   | VIC | 123451234       |             | I0036534915 | Y         |                 |         |           |                 |         |           |                 |         |           |                 |         | A          |                 | C             | AUD          | N                   | 4000.000000 | 4000.000000  | 1            | 30.00          | 1000.000000   | 1000.000000 | 30000.00    |                 |                    | 19000.00   |         | 90.00         | 100.00        | 15.00         | 19.00    | 10776.00          |              |                     | C             | C             | 20/08/2015 | 10          | 00          | 20/08/2015     | 1000.000000 | 1000.000000 | 30000.00  | 30.000000  | 30.000000  | 30.000000    | 30000.00    |                 | 205.00         |            | 19.00 |             | 10776.00   | 90.00          | 100.00         |                |                | 15.00          |                | 1             | 10776.00           |                 |                   |           |                |                    |                   |               |                    |                |            | 205.00        | 19.00     |               |           |                |          |              |               | TSSAL           | OPT1    | NDF   | OPT       | 1         | 1000.000000      |           |         | 20/08/2015     | 20/08/2015   | S              | S              |           | Settled | 30.000000 | 1          | 1000.000000 | 10776.00   | Y           | Cheque Loc        | AUD      | 1000.000000 | Sell All  | S        | SALE         | Settled    | 1          | 1000.000000     | 10776.00   | 20/08/2015         | 20/08/2015           | ESSOPT             |                 | 1.000000    | 99999999999.000000 | 10:00      | ORD               | VIC                 | Market     |       |       |       |       |       | 01     |                | 20/08/2015  | AUSTRALIAN DOLLAR | Cheque/Unpres  | 205.00       | 19.00       | R              | R              | TH      | /OPT            |          |                    |             |                  |               |                  |                 | ROPT             | 1000.000000 | 10776.00   | NAB2_AUTO  |


@TS_TradingSystemGold
@LoanPlanSales
@30881
Scenario Outline: Loan Real Time Sale EndtoEnd
	Given I have connected to WinForms
	When In SELCOY01 I select the company as "<COY>"
		#And I go to "Company Options" Control Code Menu
		#And In HKS01516 I set the Multi-Cert Flag to "<Multi-Cert>"
		And I go to "Trading Control Codes" Control Code Menu
		And In TRD24000 I select the Trade Control Code "<tradeControlCode>"
		And In TRD24001 I perform a Change for On Market Trade "<OnMarketTrade>", "<BrokerCode>", "<BrokerAccountID>", "<ConnectionCode>", "<RealTimeTrading>" and Top Up "<TopupPercentage>", "<SellSelected>" and Remaining Balance Options "<Option>", "<TranType>", "<Class>", "<Reg>" and World Link Number "<WorldLinkNumber>"
		And I go to the Trading system Sales and trade control code "<tradeControlCode>"
		And In TRS00501 I Add Postal Transaction Entry details as "<SearchName>" 
		And In TRS00502 I Add Postal Transaction Entry details as "<SellOption>" "<Units>" "<PaymentMethod>" "<PrefCurrency>" "<NotificationReqdInd>" "<Balance>" "<AvailBalance>"	
		And In TRS00507 I Add Postal Transaction Entry details as "<SellAll01>" "<Units01>" "<SellAll02>" "<Units02>" "<SellAll03>" "<Units03>" "<SellAll04>" "<Units04>" "<SellAll05>" "<Units05>" "<SellAll06>" "<Units06>" "<SellAll07>" "<Units07>" "<SellAll08>" "<Units08>" "<SellAll09>" "<Units09>"
		And In TRS00511 I Add Postal Transaction Entry details as "<DurationType>" "<EstMarketValue>"
		And In TRS00513 I Add Postal Transaction Entry details as "<Cover01>" "<Cover02>" "<Cover03>" "<Cover04>" "<Cover05>" "<Cover06>" "<Cover07>" "<Cover08>" "<Cover09>" "<Cover10>" "<Cover11>" "<Cover12>" "<Cover13>" "<Cover14>" "<Cover15>"
		And In TRS00504 I Verify Postal Transaction Entry details as "<UnitsSell>" "<EstMarketValue>" "<MarketValue>" "<PurchResidueAmt>" "<FederalTaxWithheld>" "<LoanAmt>" "<ChargeAmount1>" "<ChargeAmount2>" "<ChargeAmount3>" "<TotalGst>" "<EstimatedProceeds>"
		And In TRS00512 I Add Postal Transaction Entry details as "<OverrideEmailInd>" "<EmailAddress>"
		And In TRS00503 I Add Postal Transaction Entry details as "<ConfirmUnits>" "<ConfirmWarningFlag5>"
		And In TRD00401 I Change Order Status to "<MenuSelection>" "<ConfirmStatus>" "<TradeDate>" "<TradeTimeHH>" "<TradeTimeMM>" "<SettlementDate>" "<FinalPrice>"
	Then In TRD004CS I Verify Change Order Status details1 as "<UnitsTraded>" "<TotalCost>" "<FinalPrice>" "<TradePrice>" "<PriceATAudit>" "<GrossAmount>" "<PurchaseResidue>" "<HolderCharges1>" "<LoanAmount>" "<OptionCost>" "<Gst>" "<TaxWithheld>" "<NettAmount>" "<ChargeAmount01>" "<ChargeAmount02>" "<ChargeAmount03>" "<ChargeAmount04>" "<ChargeAmount05>" "<ChargeAmount06>"
		And In TRD004CS I Verify Change Order Status details2 as "<LocalChqCount>" "<LocalChqNettAmount>" "<ForeignChqCount>" "<ForeignChqNettAmt>" "<WireCount>" "<WireNettAmount>" "<DirectBankingCount>" "<DirectBankNettAmt>" "<EmployerCount>" "<EmployerNettAmount>" "<CompanyCharges>" "<CompanyTax>" "<HolderCharges>" "<HolderTax>" "<ReportCharges>" "<ReportTax>" "<BankType>" "<BranchNumber>" "<AccountNumber>"
	When In TRD00101 I Run the Generate Output Job as "<PaymentAccount1>" "<OrderNO>" "<Ident>" "<ClassCode>" "<NbrTrades>" "<TradeGrossAmount>" "<TradeFrom>" "<TradeTO>" "<SettlementFrom>" "<SettlementTO>"
		And I wait for  GenerateOutput job to complete
			| PassCriteria | timeout | FailCriteria | PassCriteriaLNX | FailCriteriaLNX |
			| completion   | 240     | error        | DONE            | EXIT            |			
		And In TRD00401 I Force Settle the Order as "<MenuSelection1>" "<ConfirmStatus1>"
	Then In TRS01010 I Verify Transaction Enquiry details as "<TradingID>" "<Status>" "<Price>" "<ClassCode>" "<TransCount>" "<TransTotal>" "<MoneyTotal>" "<SettlementDate>" "<ApplyTaxInd>" "<PaymentMethod>" "<PaymentMethodDesc>" "<Currency>" "<SellUnits>" "<OrderType>" "<TradeUnits>" "<TradeMoney>"
		And In TRDSCH02 I Verify Transaction Enquiry details as "<TradingID>" "<BulkType>" "<BulkTypeDesc>" "<StatusDesc>" "<TotalCount>" "<OrderTransUnits>" "<TotalMoney>" "<TradeDate>" "<ReqdSettlementDate>" "<ActualSettlementDate>" "<FinalPrice>" "<ReconciliationCode>" "<CshtrnReference>" "<MinimumDeal>" "<MaximumDeal>" "<CutOffTime>" "<CounterpartyClass>" "<CounterRegisterCode>" "<OrderType1>"
		And In TRDSCHCS I Verify Transaction Enquiry details1 as "<UnitsTraded>" "<TotalCost>" "<FinalPrice>" "<PriceATAudit>" "<GrossAmount>" "<PurchaseResidue>" "<HolderCharges1>" "<LoanAmount>" "<OptionCost>" "<Gst>" "<TaxWithheld>" "<NettAmount>" "<ChargeAmount01>" "<ChargeAmount02>" "<ChargeAmount03>" "<ChargeAmount04>" "<ChargeAmount05>" "<ChargeAmount06>"
		And In TRDSCHCS I Verify Transaction Enquiry details2 as "<LocalChqCount>" "<LocalChqNettAmount>" "<ForeignChqCount>" "<ForeignChqNettAmt>" "<WireCount>" "<WireNettAmount>" "<DirectBankingCount>" "<DirectBankNettAmt>" "<EmployerCount>" "<EmployerNettAmount>" "<CompanyCharges>" "<CompanyTax>" "<HolderCharges>" "<HolderTax>" "<ReportCharges>" "<ReportTax>" "<BankType>" "<BranchNumber>" "<AccountNumber>"
		And I go the Main Menu From Trading System
	#Given I have connected to WinForms
	When In SELCOY01 I select the company as "<COY>"
		And I go to the Enquiry system and Search <SearchName>
		And I enter the following details as the Locate action:
				| Field           | Value |
				| Action          | TH    |
				| Locate Argument | /ELA  |	 
	Then In ENSTRD48 I should see trading history summary as "<Line1>" "<Line2>" "<Line3>" "<Line4>" "<Line5>"	
	When I enter the following details as the locatActions "<Action>"  "<LocateArgument>"
		And In ENSTRDSH I Verify Trade History details1 as "<TotalUnits>" "<UnitsSell>" "<FinalPrice>" "<GrossAmount>" "<PurchaseResidue>" "<LoanAmount>" "<OptionCost>" "<Gst>" "<TaxWithheld>" "<NettAmount>" "<ChargeAmount01>" "<ChargeAmount02>" "<ChargeAmount03>" "<ChargeAmount04>" "<ChargeAmount05>" "<ChargeAmount06>" "<PaymentDate>" "<PaymentAccount>" 
		And In ENSTRDSH I Verify Trade History details2 as "<PrefCurrency>" "<CurrencyDesc>" "<PaymentMethod1>" "<HolderCharges>" "<HolderTax>" "<CompanyCharges>" "<CompanyTax>" "<ReportCharges>" "<ReportTax>" "<TotalCharges>" "<GstTaxTotal>" "<BankCode>" "<PayeeAccountNumber>" "<AccountName>" "<RemainingBalance>" "<RemBalIndDesc>" "<TransfereeHolder>" "<TransfereeClass>"
	Then I copy output files to local
		| ReportHeading   | FileName | COY   | CurrentCOY   |
		| <ReportHeading> |          | <COY> | <CurrentCOY> |
		And I parse the files from VMS or Linux
		And I compare the files from VMS and Linux goldcopy

Examples: 
		| ReportHeading | COY       | OnMarketTrade | BrokerCode | BrokerAccountID | ConnectionCode | RealTimeTrading | TopupPercentage | SellSelected | Option | TranType | Class | Reg | WorldLinkNumber | SearchName  | SellOption | Units | PaymentMethod | PrefCurrency | NotificationReqdInd | Balance     | AvailBalance | DurationType | EstMarketValue | UnitsSell  | MarketValue | PurchResidueAmt | FederalTaxWithheld | LoanAmt | ChargeAmount1 | ChargeAmount2 | ChargeAmount3 | TotalGst | EstimatedProceeds | OverrideEmailInd | EmailAddress               | ConfirmUnits | ConfirmWarningFlag5 | MenuSelection | ConfirmStatus | TradeDate  | TradeTimeHH | TradeTimeMM | SettlementDate | TotalUnits | UnitsTraded | TotalCost | FinalPrice | TradePrice | PriceATAudit | GrossAmount | PurchaseResidue | HolderCharges1 | LoanAmount | OptionCost | Gst   | TaxWithheld | NettAmount | ChargeAmount01 | ChargeAmount02 | ChargeAmount03 | ChargeAmount04 | ChargeAmount05 | ChargeAmount06 | LocalChqCount | LocalChqNettAmount | ForeignChqCount | ForeignChqNettAmt | WireCount | WireNettAmount | DirectBankingCount | DirectBankNettAmt | EmployerCount | EmployerNettAmount | CompanyCharges | CompanyTax | HolderCharges | HolderTax | ReportCharges | ReportTax | PaymentAccount | BankType | BranchNumber | AccountNumber | PaymentAccount1 | OrderNO | Ident | ClassCode | NbrTrades | TradeGrossAmount | TradeFrom | TradeTO | SettlementFrom | SettlementTO | MenuSelection1 | ConfirmStatus1 | TradingID | Status  | Price     | TransCount | TransTotal | MoneyTotal | ApplyTaxInd | PaymentMethodDesc | Currency | SellUnits  | OrderType    | BulkType | BulkTypeDesc | StatusDesc | TotalCount | OrderTransUnits | TotalMoney | ReqdSettlementDate | ActualSettlementDate | ReconciliationCode | CshtrnReference | MinimumDeal | MaximumDeal        | CutOffTime | CounterpartyClass | CounterRegisterCode | OrderType1 | Line1                                                                                            | Line2 | Line3 | Line4 | Line5 | Action | LocateArgument | PaymentDate | CurrencyDesc      | PaymentMethod1 | TotalCharges | GstTaxTotal | BankCode | PayeeAccountNumber | AccountName               | Cover01 | Cover02 | Cover03 | Cover04 | Cover05 | Cover06 | Cover07 | Cover08 | Cover09 | Cover10 | Cover11 | Cover12 | Cover13 | Cover14 | Cover15 | UnitsTraded1 | SellAll01 | Units01 | SellAll02 | Units02 | SellAll03 | Units03 | SellAll04 | Units04 | SellAll05 | Units05 | SellAll06 | Units06 | SellAll07 | Units07 | SellAll08 | Units08 | SellAll09 | Units09 | RemainingBalance | RemBalIndDesc | TransfereeHolder | TransfereeClass | tradeControlCode | TradeUnits | TradeMoney | CurrentCOY |
		| SellPartial   | NAB2_AUTO | M             | 3383       | CLS.GAP         | ORMSAUUAT      | Y               | 0.00            | Y            | C      | ESTSC    | ORD   | VIC | 123451234       | I0036534010 | P          | 750   | D             | AUD          | E                   | 1500.000000 | 1500.000000  | 1            | 30.00          | 750.000000 | 22500.00    |                 |                    | 2000.00 | 67.50         | 100.00        | 10.00         | 16.75    | 20305.75          | N                | REAL-TIME-HOLDER2@TEST.COM | 750.000000   |                     | C             | C             | 20/08/2015 | 10          | 00          | 20/08/2015     | 750.000000 | 750.000000  | 22500.00  | 30.000000  | 30.000000  | 30.000000    | 22500.00    |                 | 177.50         | 2000.00    |            | 16.75 |             | 20305.75   | 67.50          | 100.00         |                | 10.00          |                |                |               |                    |                 |                   |           |                | 1                  | 20305.75          |               |                    |                |            | 177.50        | 16.75     |               |           |                |          |              |               | TSSAL           | ELA2    | NDF   | ELA       | 1         | 750.000000       |           |         | 20/08/2015     | 20/08/2015   | S              | S              |           | Settled | 30.000000 | 1          | 750.000000 | 20305.75   | Y           | Dir-Credit        | AUD      | 750.000000 | Sell Partial | S        | SALE         | Settled    | 1          | 750.000000      | 20305.75   | 20/08/2015         | 20/08/2015           | ESSOPT             | 1565            | 1.000000    | 99999999999.000000 | 10:00      | ORD               | VIC                 | Market     | ELA Sale     RELA0000003  79269004 20/08/15 Set          750.000000      20305.75      30.000000 |       |       |       |       | 01     |                | 20/08/2015  | AUSTRALIAN DOLLAR | Direct Banking | 177.50       | 16.75       | 013-481  | 000000000145214177 | MR REAL-TIME LOAN-HOLDER2 |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         | 750.000000   |           |         |           |         |           |         |           |         |           |         |           |         |           |         |           |         |           |         |                  |               |                  |                 | RELA             | 750.000000 | 20305.75   | NAB2_AUTO  |


@TS_TradingSystemGold
@RightsPlanSales
@31035
Scenario Outline: Rights Real Time Sale EndtoEnd
	Given I have connected to WinForms
	When In SELCOY01 I select the company as "<COY>"
		And I go to "Company Options" Control Code Menu
		And In HKS01516 I set the Multi-Cert Flag to "<Multi-Cert>"
		And I go to "Trading Control Codes" Control Code Menu
		And In TRD24000 I select the Trade Control Code "<tradeControlCode>"
		And In TRD24001 I perform a Change for On Market Trade "<OnMarketTrade>", "<BrokerCode>", "<BrokerAccountID>", "<ConnectionCode>", "<RealTimeTrading>" and Top Up "<TopupPercentage>", "<SellSelected>" and Remaining Balance Options "<Option>", "<TranType>", "<Class>", "<Reg>" and World Link Number "<WorldLinkNumber>"
		And I go to the Trading system Sales and trade control code "<tradeControlCode>"
		And In TRS00701 I Add Postal Transaction Entry details as "<TransNumber>" "<SearchName>" 
	#Then In TRS00711 I Verify Certificate Selection details as "<CertID1>" "<Register1>" "<OptionPrice1>" "<CertBalance1>" "<AvailBal1>" "<CertID2>" "<Register2>" "<OptionPrice2>" "<CertBalance2>" "<AvailBal2>"
	When In TRS00702 I Add Postal Transaction Entry details as "<SellOption>" "<RemainingBalInd>" "<PaymentMethod>" "<PrefCurrency>" "<NotificationReqdInd>" "<Balance>" "<AvailBalance>"		
		And In TRS00707 I Add Postal Transaction Entry details as "<SellAll01>" "<ExerciseUnits01>" "<Units01>" "<SellAll02>" "<ExerciseUnits02>" "<Units02>" "<SellAll03>" "<ExerciseUnits03>" "<Units03>" "<SellAll04>" "<ExerciseUnits04>" "<Units04>"
		And In TRS00511 I Add Postal Transaction Entry details as "<DurationType>" "<EstMarketValue>"
		And In TRS00704 I Verify Postal Transaction Entry details as "<UnitsExercise>" "<UnitsSell>" "<EstMarketValue>" "<MarketValue>" "<PurchResidueAmt>" "<FederalTaxWithheld>" "<OptionCost>" "<ChargeAmount1>" "<ChargeAmount2>" "<ChargeAmount3>" "<TotalGst>" "<EstimatedProceeds>"
		And In TRS00703 I Add Postal Transaction Entry details as "<ExerciseUnits>" "<ConfirmUnits>" "<ConfirmWarningFlag5>"
		And In TRD00401 I Change Order Status to "<MenuSelection>" "<ConfirmStatus>" "<TradeDate>" "<TradeTimeHH>" "<TradeTimeMM>" "<SettlementDate>" "<FinalPrice>"
	Then In TRD004CS I Verify Change Order Status details1 as "<UnitsTraded>" "<TotalCost>" "<FinalPrice>" "<TradePrice>" "<PriceATAudit>" "<GrossAmount>" "<PurchaseResidue>" "<HolderCharges1>" "<LoanAmount>" "<OptionCost>" "<Gst>" "<TaxWithheld>" "<NettAmount>" "<ChargeAmount01>" "<ChargeAmount02>" "<ChargeAmount03>" "<ChargeAmount04>" "<ChargeAmount05>" "<ChargeAmount06>"
		And In TRD004CS I Verify Change Order Status details2 as "<LocalChqCount>" "<LocalChqNettAmount>" "<ForeignChqCount>" "<ForeignChqNettAmt>" "<WireCount>" "<WireNettAmount>" "<DirectBankingCount>" "<DirectBankNettAmt>" "<EmployerCount>" "<EmployerNettAmount>" "<CompanyCharges>" "<CompanyTax>" "<HolderCharges>" "<HolderTax>" "<ReportCharges>" "<ReportTax>" "<BankType>" "<BranchNumber>" "<AccountNumber>"
	When In TRD00101 I Run the Generate Output Job as "<PaymentAccount1>" "<OrderNO>" "<Ident>" "<ClassCode>" "<NbrTrades>" "<TradeGrossAmount>" "<TradeFrom>" "<TradeTO>" "<SettlementFrom>" "<SettlementTO>"
		And I wait for  GenerateOutput job to complete
			| PassCriteria | timeout | FailCriteria | PassCriteriaLNX | FailCriteriaLNX |
			| completion   | 240     | error        | DONE            | EXIT            |
		And In TRD00401 I Apply Exercise Transaction as "<MenuSelection2>" "<ConfirmStatus2>" "<TradeDate>" "<TradeTimeHH>" "<TradeTimeMM>" "<SettlementDate>" "<FinalPrice>"
		And In TRD00401 I Force Settle the Order as "<MenuSelection1>" "<ConfirmStatus1>"
	Then In TRS01010 I Verify Transaction Enquiry details as "<TradingID>" "<Status>" "<Price>" "<ClassCode>" "<TransCount>" "<TransTotal>" "<MoneyTotal>" "<SettlementDate>" "<ApplyTaxInd>" "<PaymentMethod>" "<PaymentMethodDesc>" "<Currency>" "<SellUnits>" "<OrderType>" "<TradeUnits>" "<TransMoney>"
		And In TRDSCH02 I Verify Transaction Enquiry details as "<TradingID>" "<BulkType>" "<BulkTypeDesc>" "<StatusDesc>" "<TotalCount>" "<OrderTransUnits>" "<TotalMoney>" "<TradeDate>" "<ReqdSettlementDate>" "<ActualSettlementDate>" "<FinalPrice>" "<ReconciliationCode>" "<CshtrnReference>" "<MinimumDeal>" "<MaximumDeal>" "<CutOffTime>" "<CounterpartyClass>" "<CounterRegisterCode>" "<OrderType1>"
		And In TRDSCHCS I Verify Transaction Enquiry details1 as "<UnitsTraded>" "<TotalCost>" "<FinalPrice>" "<PriceATAudit>" "<GrossAmount>" "<PurchaseResidue>" "<HolderCharges1>" "<LoanAmount>" "<OptionCost>" "<Gst>" "<TaxWithheld>" "<NettAmount>" "<ChargeAmount01>" "<ChargeAmount02>" "<ChargeAmount03>" "<ChargeAmount04>" "<ChargeAmount05>" "<ChargeAmount06>"
		And In TRDSCHCS I Verify Transaction Enquiry details2 as "<LocalChqCount>" "<LocalChqNettAmount>" "<ForeignChqCount>" "<ForeignChqNettAmt>" "<WireCount>" "<WireNettAmount>" "<DirectBankingCount>" "<DirectBankNettAmt>" "<EmployerCount>" "<EmployerNettAmount>" "<CompanyCharges>" "<CompanyTax>" "<HolderCharges>" "<HolderTax>" "<ReportCharges>" "<ReportTax>" "<BankType>" "<BranchNumber>" "<AccountNumber>"
		And I go the Main Menu From Trading System
	#Given I have connected to WinForms
	When In SELCOY01 I select the company as "<COY>"
		And I go to the Enquiry system and Search <SearchName>
		And I enter the following details as the locatActions "<Action1>"  "<LocateArgument1>"
	Then In ENSTRD48 I should see trading history summary as "<Line1>" "<Line2>" "<Line3>" "<Line4>" "<Line5>"	
	When I enter the following details as the locatActions "<Action>"  "<LocateArgument>"
		And In ENSTRDSH I Verify Trade History details1 as "<TradeUnits>" "<UnitsSell>" "<FinalPrice>" "<GrossAmount>" "<PurchaseResidue>" "<LoanAmount>" "<OptionCost>" "<Gst>" "<TaxWithheld>" "<NettAmount>" "<ChargeAmount01>" "<ChargeAmount02>" "<ChargeAmount03>" "<ChargeAmount04>" "<ChargeAmount05>" "<ChargeAmount06>" "<PaymentDate>" "<PaymentAccount>" 
		And In ENSTRDSH I Verify Trade History details2 as "<PrefCurrency>" "<CurrencyDesc>" "<PaymentMethod1>" "<HolderCharges>" "<HolderTax>" "<CompanyCharges>" "<CompanyTax>" "<ReportCharges>" "<ReportTax>" "<TotalCharges>" "<GstTaxTotal>" "<BankCode>" "<PayeeAccountNumber>" "<AccountName>" "<RemainingBalance>" "<RemBalIndDesc>" "<TransfereeHolder>" "<TransfereeClass>"
	Then I copy output files to local
		| ReportHeading   | FileName | COY   | CurrentCOY   |
		| <ReportHeading> |          | <COY> | <CurrentCOY> |
		And I parse the files from VMS or Linux
		And I compare the files from VMS and Linux goldcopy

Examples: 
		| ReportHeading       | COY       | Multi-Cert | OnMarketTrade | BrokerCode | BrokerAccountID | ConnectionCode | RealTimeTrading | TopupPercentage | SellSelected | Option | TranType | Class | Reg | WorldLinkNumber | TransNumber | SearchName  | SellAll01 | ExerciseUnits01 | Units01 | SellAll02 | ExerciseUnits02 | Units02 | SellAll03 | ExerciseUnits03 | Units03 | SellAll04 | ExerciseUnits04 | Units04 | SellOption | RemainingBalInd | PaymentMethod | PrefCurrency | NotificationReqdInd | Balance     | AvailBalance | DurationType | EstMarketValue | UnitsExercise | UnitsSell  | MarketValue | PurchResidueAmt | FederalTaxWithheld | OptionCost | LoanAmt | ChargeAmount1 | ChargeAmount2 | ChargeAmount3 | TotalGst | EstimatedProceeds | ConfirmUnits | ConfirmWarningFlag5 | MenuSelection | ConfirmStatus | TradeDate  | TradeTimeHH | TradeTimeMM | SettlementDate | TotalUnits | UnitsTraded | TotalCost | FinalPrice | TradePrice | PriceATAudit | GrossAmount | PurchaseResidue | HolderCharges1 | LoanAmount | Gst   | TaxWithheld | NettAmount | ChargeAmount01 | ChargeAmount02 | ChargeAmount03 | ChargeAmount04 | ChargeAmount05 | ChargeAmount06 | LocalChqCount | LocalChqNettAmount | ForeignChqCount | ForeignChqNettAmt | WireCount | WireNettAmount | DirectBankingCount | DirectBankNettAmt | EmployerCount | EmployerNettAmount | CompanyCharges | CompanyTax | HolderCharges | HolderTax | ReportCharges | ReportTax | PaymentAccount | BankType | BranchNumber | AccountNumber | PaymentAccount1 | OrderNO | Ident | ClassCode | NbrTrades | TradeGrossAmount | TradeFrom | TradeTO | SettlementFrom | SettlementTO | MenuSelection1 | ConfirmStatus1 | TradingID | Status  | Price     | TransCount | TransTotal | MoneyTotal | ApplyTaxInd | PaymentMethodDesc | Currency | SellUnits  | OrderType     | BulkType | BulkTypeDesc | StatusDesc | TotalCount | OrderTransUnits | TotalMoney | ReqdSettlementDate | ActualSettlementDate | ReconciliationCode | CshtrnReference | MinimumDeal | MaximumDeal        | CutOffTime | CounterpartyClass | CounterRegisterCode | OrderType1 | Line1 | Line2 | Line3 | Line4 | Line5 | Action | LocateArgument | PaymentDate | CurrencyDesc      | PaymentMethod1 | TotalCharges | GstTaxTotal | MenuSelection2 | ConfirmStatus2 | Action1 | LocateArgument1 | BankCode | PayeeAccountNumber | AccountName | RemainingBalance | RemBalIndDesc | TransfereeHolder | TransfereeClass | tradeControlCode | TradeUnits | TransMoney | CurrentCOY |
		| ExerciseSelectedWHT | NAB2_AUTO | N          | M             | 3383       | CLS.GAP         | ORMSAUUAT      | Y               | 0.00            |              | C      | ESOXR    | ORD   | VIC | 123451234       |             | I0036536314 |           |                 |         |           |                 |         |           | 799             |         |           |                 |         | A          |                 | E             |              | N                   | 4000.000000 | 3900.000000  | 1            | 30.00          | 799.000000    | 799.000000 | 23970.00    |                 | 12426.04           |            |         | 71.91         | 100.00        |               | 17.19    | 11354.86          |              |                     | C             | C             | 20/08/2015 | 10          | 00          | 20/08/2015     | 799.000000 | 799.000000  | 23970.00  | 30.000000  | 30.000000  | 30.000000    | 23970.00    |                 | 171.91         |            | 17.19 | 12426.04    | 11354.86   | 71.91          | 100.00         |                |                |                |                |               |                    |                 |                   |           |                |                    |                   | 1             | 11354.86           |                |            | 171.91        | 17.19     |               |           |                |          |              |               | TSSAL           | RGT4    | NDF   | PRS       | 1         | 799.000000       |           |         | 20/08/2015     | 20/08/2015   | S              | S              |           | Settled | 30.000000 | 1          | 799.000000 | 11354.86   | Y           | Employer          | AUD      | 799.000000 | Sell Specific | S        | SALE         | Settled    | 1          | 799.000000      | 11354.86   | 20/08/2015         | 20/08/2015           | ESSOPT             |                 | 1.000000    | 99999999999.000000 | 10:00      | ORD               | VIC                 | Market     |       |       |       |       |       | 01     |                | 20/08/2015  | AUSTRALIAN DOLLAR | Employer       | 171.91       | 17.19       | R              | R              | TH      | /PRS            |          |                    |             |                  |               |                  |                 | RPRS             | 799.000000 | 11354.86   | NAB2_AUTO  |
